### ISSUE TITLE
Useless and irritating message entering a date format

### ISSUE THREAD

**Issue by Presskopp** [Mte90/GlotDict#101]
Browser: **Chrome**
Link: https://translate.wordpress.org/projects/meta/themes/de/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4817697&filters%5Btranslation_id%5D=50649123
Locale used: **de_DE**

Translating "F j, Y" to "j. F Y" you get a warning "The translation is missing an initial uppercase letter for "j"

Maybe Date-Formats can be put on a 'whitelist' or st.

http://imgur.com/a/xKHbA

**Comment by Mte90** [comment]
Good point the problem is how I can understand if the string contain a date format for php from js?
Actually I don't find a solution for that :-/

**Comment by Mte90** [comment]
I studied a little and I cannot do anything for that :-/
I find few libraries that add the php support for date time format to javascript but do a check for everything can slow down the performance and creates new problems :-/
The best will have a check inside GlotPress, I will open a request to them :-)
