### ISSUE TITLE
Enhancement: Disable 'Review in progress' upon click

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#102]
Browser: Chrome
Link: https://translate.wordpress.org/projects/wp-plugins/easy-digital-downloads/dev-readme/en-ca/default
Locale used: en_CA

Hi @Mte90 thanks for adding the 'Review in progress' to the button to denote review mode. Clicking it again however doesn't change the text back or maybe is there no way to disable review mode once it's entered (aside from reload)??

THanks

**Comment by Mte90** [comment]
No there is no way actually to disable on running the only one is to refresh the page.
I have to improve the UI

**Comment by garrett-eclipse** [comment]
kk wasn't sure thanks for confirming

**Comment by Mte90** [comment]
The best will be to open an alert about asking user if he want to refresh the page on clicking again in the button.

**Comment by garrett-eclipse** [comment]
For sure, thinking either reload page when you click it again or add a 'Cancel' link when in review mode which will refresh the page.

**Comment by garrett-eclipse** [comment]
Thanks @Mte90
