### ISSUE TITLE
Suppress Review Action Buttons on non-review rows

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#108]
Browser: Chrome
Link: https://translate.wordpress.org/projects/wp-plugins/woo-pelecard-gateway/dev-readme/en-ca/default
Locale used: en_CA

Hi @Mte90 

Love the idea behind 1.3.6 can see that being very useful for reviews.

However on non-review rows might be a good idea to suppress or will result in lots of errors when clicked;
![screen shot 2017-08-10 at 3 33 17 pm](https://user-images.githubusercontent.com/8726005/29195078-81134fec-7de1-11e7-9bed-ffc48f41e441.png)
*If you're on an untranslated row and click any of the actions results in Errors.

Hope that makes sense,
Cheers

**Comment by garrett-eclipse** [comment]
One additional nuance to this is if you have a non-review row that has a current translation then the Approve action should be suppressed as the only valid actions in this case are Reject and Fuzzy;
![screen shot 2017-08-10 at 3 38 34 pm](https://user-images.githubusercontent.com/8726005/29195190-00452498-7de2-11e7-987e-be400399b322.png)

**Comment by Mte90** [comment]
Yes you are right, I will work on that today :-D

**Comment by garrett-eclipse** [comment]
Nice, thanks @Mte90
