### ISSUE TITLE
Submitting Translation results in action columns becoming empty

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#109]
Browser: Chrome
Link: https://translate.wordpress.org/projects/wp-plugins/simple-download-monitor/dev-readme/en-ca/default?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
Locale used: en_CA

Hi @Mte90,

Another minor item, when you submit a translation the action columns becomes empty. As you're submitting a current translation maybe drop the Approve and keep the Reject and Fuzzy actions as those are valid actions on a current string.
![screen shot 2017-08-10 at 3 37 30 pm](https://user-images.githubusercontent.com/8726005/29195236-3c9434c0-7de2-11e7-86d3-e22160cbefd5.png)

Cheers

**Comment by Mte90** [comment]
Yes I know that problem but for the moment I didn't find a way to readd the buttons but I will continue to work on that

**Comment by garrett-eclipse** [comment]
Nice mate you're on fire today ;)
