### ISSUE TITLE
Count words

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#112]
By selection or by the area

**Comment by Mte90** [comment]
As UX I can do it on the contextmenu

**Comment by Nitiquita** [comment]
@Mte90 can you give more details about this issue?

**Comment by Mte90** [comment]
The idea is about strings on translate.wordpress.org and you maybe want to see that value but we need to define where in the UI

**Comment by garrett-eclipse** [comment]
@Mte90 I would just suggest implementing into the Meta and providing both the original string count and the translated string count. Just my 2 cents

**Comment by garrett-eclipse** [comment]
I've added PR #163 to accommodate this by introducing a String Counts section to the Meta on Editor rows. The character count is displayed by default with word count available on hover. 
![string count](https://user-images.githubusercontent.com/8726005/42490074-50998f96-83c3-11e8-977f-fa2745c22396.png)
