### ISSUE TITLE
Impossible to save

### ISSUE THREAD

**Issue by fxbenard** [Mte90/GlotDict#117]
Browser: FF
Link: everywhere
Locale used: fr_FR

When the option: No glossary term missing warning on translation is checked, I can’t save any new translations.
removing the option, no problem to save any new translations.
FYI: GTE speaking here

Happy bug fixing

**Comment by garrett-eclipse** [comment]
This seems to be another complication stemming from issue #95 
Until @Mte90 can address you can go to the GlotDict options and disable that warning.
Simply click 'GlotDict' to view options and uncheck 'No glossary term missing warning on translation'

Hope that helps get you back to translating until it can be properly resolved

**Comment by Mte90** [comment]
I will check that issue tomorrow :-)

**Comment by Mte90** [comment]
The https://github.com/Mte90/GlotDict/commit/428b4245667f22b99dd052c8dd03847988657200 commit fix that problem
