### ISSUE TITLE
Improve copy for warning of terms

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#118]
Actually on https://github.com/Mte90/GlotDict/blob/master/js/glotdict-validation.js#L50 there is that label that create confusion:

`The translation is missing of the translation term [wrongtranslatedterm] for "<i>[terminthesitring]</i>"`

Actually show the term configured in the glossary for that but can be wrong for plurals etc.
It is required a new copy, someone has suggestions?

**Comment by Mte90** [comment]
* is missing the suggested translation

**Comment by jyourstone** [comment]
Seeing as translations differ vastly from language to language and one word in English can have multiple meanings in another language, I would suggest removing this feature all together until GlotPress becomes "smarter" (can handle plurals, match several translations etc.). 
Or at least have an option to always hide that specific error message.

**Comment by Mte90** [comment]
This feature is useful to check wrong terms that can happen for that reason there is a flag to disable without removing.
We can improve the copy and in the meantime keep that feature.

**Comment by jyourstone** [comment]
Where is the flag to disable without removing? I can't seem to find the GlotDict options since it's greyed out in Chrome. I can only click "Discard" for each of the warning, not remove the warnings permanently.

**Comment by Mte90** [comment]
I showed during the video yesterday the button, there is also an alert on the right to remind the settings.
In the blu header bar on the top on the right you can find GlotDict

**Comment by jyourstone** [comment]
Yes but that blue header didn't show up when I installed the extension. But I forgot to try a reboot and now I can see it, sorry about the trouble and thank you for your help.
