### ISSUE TITLE
Warning of terms when multiple identical terms in Glossary

### ISSUE THREAD

**Issue by jyourstone** [Mte90/GlotDict#119]
If the Glossary contains several identical source words with different translations, GlotDict still shows a warning message even though the translation is correct.

![error message](https://user-images.githubusercontent.com/4037547/31114826-1fc4178a-a820-11e7-8698-3c48cfa998ca.jpg)
![error message 2 underlined](https://user-images.githubusercontent.com/4037547/31114828-2223b0a8-a820-11e7-9e49-1d78fe9b464c.jpg)
![error message 3 underlined](https://user-images.githubusercontent.com/4037547/31115056-19f81832-a821-11e7-808c-7912887f2afb.jpg)
![error message 4 underlined](https://user-images.githubusercontent.com/4037547/31115058-1b1de43a-a821-11e7-8a19-498aaab5925f.jpg)

**Comment by Mte90** [comment]
Ok for the same term translation seems that the validation broken on the first check and not on all the terms.
Can you give me a like where it is happen so I can replicate and fix it?

**Comment by jyourstone** [comment]
I marked the string in the screenshots as fuzzy to find it easier, direct link: https://translate.wordpress.org/projects/wp-plugins/multisite-post-duplicator/dev/sv/default?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=fuzzy
