### ISSUE TITLE
Make a language choice by default

### ISSUE THREAD

**Issue by fxbenard** [Mte90/GlotDict#12]
I'm using fr_FR as a GTE, it will be perfect to have an option to choice it forever in the plugin option page. and if the option is setup to remove the dropdown in the page.

**Comment by Mte90** [comment]
Actually the language when you choose one remember that settings for all the pages.
So do you have problem with that part? Or you prefer to move that settings in a browser panel?

**Comment by fxbenard** [comment]
Nope, settings aren't saved, I have to choose fr_FR on every pages or refresh. When I open a page it's de_DE is selected in the dropdown and it's the de_DE glossary.

I thing moving the settings in the plugin panel will be neat. If the settings are saved correctly. Use it and forget it

By the way, nice peace of a plugin you created here.
FYI I'm on FF of course

**Comment by Mte90** [comment]
Asap I will do debug for that problem :-)

**Comment by fxbenard** [comment]
Lovely, I will promote your plugin on my wptranslationday session on Sunday ;)
A tool to update the glossary easily will be nice also.

**Comment by Mte90** [comment]
I tried now in Firefox and that problem is happening when you switch from different projects on translate.wordpress.org.
For the glossaries with @ePascalC I'm working to a cli script that download automatically from wordpress.org the glossaries.

**Comment by Mte90** [comment]
Uhm i trying to replicate the problem but without success but I try to improve the interla system to avoid that problem.

**Comment by fxbenard** [comment]
OK thanks, the ASAP was really fast. Yes as GTE I'm switching from project to project, from tab to tab. Problem with another plugin maybe?

Lovely news for the cli script

**Comment by Mte90** [comment]
There was a bug when switching from different pages, now is fixed.
I publish the new version today so for the wp translation day will be available.
