### ISSUE TITLE
Warning about validation

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#121]
If you are translating and press add translation you can get a warning if there are terms hightlighted.
In this workflow this is strange you need to get warnings about discard warnings if there aren't.

The ideal is to get warnings on add translation with a settings to disable it.

**Comment by Mte90** [comment]
I am trying to replicate the issue but is not happening for me with strings with terms when they are not available in the translated strings

**Comment by garrett-eclipse** [comment]
Hey @Mte90 if this is the issue I think it is... then it's one of my personal frustrations with the GlotDict warnings and their need to be dismissed before submission.

I definitely find it jarring especially with certain Glossary Terms like 'Check' which only in monetary terms in 'Cheque' in en_CA. This one I find I have to dismiss two warnings to get anything submitted.

So if I start with a new translation with 'check' in the string but leave as is;
<img width="845" alt="screen shot 2018-07-05 at 2 26 47 am" src="https://user-images.githubusercontent.com/8726005/42315007-32197d9a-7ffb-11e8-9979-438ebe7e6b57.png">

Then when I submit I get the alert;
<img width="485" alt="screen shot 2018-07-05 at 2 26 54 am" src="https://user-images.githubusercontent.com/8726005/42315026-3a37ad30-7ffb-11e8-9416-0438086f4270.png">

And then I get the warning that I have to dismiss before submitting again;
<img width="842" alt="screen shot 2018-07-05 at 2 27 00 am" src="https://user-images.githubusercontent.com/8726005/42315047-48ef6688-7ffb-11e8-9bf6-ff64a7feaf1f.png">

This basically doubles the time for making this translation. I'd almost say drop the alert all together. or make it a dismissable gp notice as they're less intrusive and can be ignored.

**Comment by Mte90** [comment]
I agree if we can do that will be better, I added the alert to avoid errors with multiple warnings and to give tothe user an alert about what is happening instead nothing.

**Comment by garrett-eclipse** [comment]
Sounds good, I've self-assigned and will update to a gp notice.

One question I did have was the difference between a GlotPress and GlotDict warning is when they are triggered.
GlotPress - triggers after submit so doesn't block the action and add the entry to the Warnings view
GlotDict - triggers on submit and blocks the action

Is that a limitation of the extension as it's JS based so without a GlotPress update can't set persistent warnings on translations.

If persistent after-submit warnings are possible with GlotDict that might be a better option for the glossary warnings.

**Comment by garrett-eclipse** [comment]
I've switched it to a GlotPress error notice and updated the verbiage for now.

If my other question is a possibility we can break it off into another ticket.

**Comment by Mte90** [comment]
I think that to simplify the extension code is better to not have persistent warnings because is something thatn eed to be implemented on GlotPRess.
For that reason I was blocking the execution of the GP warnings. Maybe we can ignore the GD but not GP because we don't have power on that.
In any case better to do another ticket :-)

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 

I've branched into a new ticket for investigation, I don't feel it should be part of 1.4 though so can go into a future milestone for investigation and most likely will require an update to GlotPress to support it.
