### ISSUE TITLE
Blocked from translating strings on specific project

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#122]
Browser: Chrome Version 62.0.3202.75 (Official Build) (64-bit)
Link: https://translate.wordpress.org/projects/wp-plugins/adsense-plugin/stable/en-ca/default?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
Locale used: en_CA

Hi @Mte90 I came across an odd issue blocking me from translating a specific project. If I switch to incognito which doesn't have GlotDict enabled then I have no issues, which is why this is opened on GlotDict and not GlotPress.

So what happens is when I submit a string I get a red error message;
![screen shot 2017-11-09 at 2 22 01 pm](https://user-images.githubusercontent.com/8726005/32632682-6463d5be-c559-11e7-9880-c2478347a738.png)

Inspecting I see an ERR_BLOCKED_BY_CLIENT;
![screen shot 2017-11-09 at 2 23 03 pm](https://user-images.githubusercontent.com/8726005/32632728-8cc0d8c2-c559-11e7-97bc-34d4528ec0e8.png)

This happened on all sub-projects of this project.

Any ideas? Let me know if I can help troubleshoot.

Cheers

**Comment by garrett-eclipse** [comment]
Scatch this sorry, I found the issue was with AdBlocker as the plugin has 'ad' in the name 'adsense-plugin' my AdBlocker extension blocked that POST. And that extensions also isn't enabled on incognito which is why it worked there. Cheers

**Comment by Mte90** [comment]
No worry!
This need to be added in the polyglots rule to disable adblocker on translate.wp.org :-)
