### ISSUE TITLE
As a translator I wish I could close the info message so it does not bother me during work

### ISSUE THREAD

**Issue by sgelob** [Mte90/GlotDict#126]
Browser: All
Link: On every page
Locale used: Italian

![screen shot 2018-01-05 at 3 23 54 pm](https://user-images.githubusercontent.com/6544108/34613080-c44833ee-f22c-11e7-8db6-ff63c29342ff.png)

**Comment by Mte90** [comment]
Good point, I can add a settings for that or someone else want to do that
