### ISSUE TITLE
Highlight non-breaking space in string details panel

### ISSUE THREAD

**Issue by audrasjb** [Mte90/GlotDict#127]
Hi @Mte90 

A fr_FR translator submitted an improvement to the non-breaking spaces highlighting feature. It would be great to show non-breaking spaces in details panel too:
![highligthed-space-in-detail-panel](https://user-images.githubusercontent.com/1590998/34651001-54ab9ffe-f3ca-11e7-9efc-766313dcfe2e.png)

I'm going to reuse our existing JS function to make a PR ;)

**Comment by Mte90** [comment]
Cool!
