### ISSUE TITLE
Absent description on how to select the glossary

### ISSUE THREAD

**Issue by sgelob** [Mte90/GlotDict#13]
Hey, several people today at Global WordPress Translation Day asked on how to change glossary, because the default glossary is the first in the list, and everybody see the cyrillic and don’t know how to change. The select field is not so visible and you need to discover it on your own.

Please, add this passage in the description after installation process ;)

Thank you in advance ;)

**Comment by Mte90** [comment]
I'm studying for that to maintain the extension light.
Maybe a little internal tooltip is the best way

**Comment by sgelob** [comment]
Nice ;) Maybe a popup after the first install and text inviting the user to select the appropriate glossary directly.

**Comment by Mte90** [comment]
![qm5](https://cloud.githubusercontent.com/assets/403283/14768414/d28018ac-0a41-11e6-85ed-5adce5a911b5.png)
I resolved in this way, the message is showed only on missing language and on first use no language is configured so the user have to choosen and we avoid that problems.
