### ISSUE TITLE
Bad User experience with warnings. 

### ISSUE THREAD

**Issue by 00travelgirl00** [Mte90/GlotDict#130]
Browser: Chrome
Link: <where happen the issue>
Locale used:

Hey, 
I have struggled in GlotPress and GlotDicwhen having an error/warning in a translation. 

If I accidentally have an error (like ending on new line and so on), I got a warning. 

If I change the mistake and want to save it, I can't, because I have to close the warning first:

"You need to close the warning to approve the new string!"

Problem is, I can't close the warning. 

So I have to reload and reject my further translation and insert my translation again. 

Also when I have selected "untranslated strings only", I can't see this string again, when reloading. I have to select "All" and search for my string to edit it again. 

I not even have found out, how to do this process in a simpler way, I just click around, till I can edit it again. Really annoying. 

I have created a screen cast of this:

https://youtu.be/yUeDrdxCZIY 

Somebody point it out, that I can't disable that setting somewhere, but this is so frustating, that it should not be default. 

I would expect this behavoir:

I suggest an translation. 
I can't save it because of an warning.
I correct my translation directly
I can save it. 

Thanks :-)

**Comment by Mte90** [comment]
Very strange, maybe you spot a bug because you have to dismiss the warning.
For the settings, yes you can disable the warnings but will be global. 
So maybe, yes there is a bug.
I will check the next week (I will be busy this week for a conf).

**Comment by 00travelgirl00** [comment]
Problem is, I can't dismiss the warning. 
No hurry, thanks for this extension btw :-)

**Comment by Mte90** [comment]
On my tests the warning is showed after the save and has the discard button.
In any case the issue is that appear after the save.
I am working on that to fix it soon!
