### ISSUE TITLE
Settings strings improvements

### ISSUE THREAD

**Issue by fxbenard** [Mte90/GlotDict#131]
Mille grazie @zetaraffix

1 - Don’t validate strings ending with “...“, “.”, “:”
2 - Don’t validate strings ending with ;.!:、。؟？！
3 - No warning for missing uppercase first character in translation
4 - No warning for missing glossary term in translation
5 - Don’t visualize non-breaking-spaces in preview
6 - Show warning for trailing space in translation
7 - Show warning for missing curly apostrophe in preview
8 - Hide Info messages about this menu

@audrasjb ping

**Comment by audrasjb** [comment]
Hi @fxbenard and many thanks, seems perfect.
@Mte90 I'm working on this right now ;)

**Comment by audrasjb** [comment]
> 6 - Show warning for trailing space in translation
I replaced "Show" with "Hide". @fxbenard are you ok with this?
Diff file below:
[131.diff.txt](https://github.com/Mte90/GlotDict/files/1716303/131.diff.txt)

**Comment by fxbenard** [comment]
@audrasjb Yes perfect

**Comment by Mte90** [comment]
Mercì!
