### ISSUE TITLE
Enhancement: add a way to translate Glotdict strings

### ISSUE THREAD

**Issue by audrasjb** [Mte90/GlotDict#134]
Hi,

What about adding a way to translate Glotdict itself? 😊
I can work on a workaround for this project, based on text files (no other idea to achieve it yet). 
Any thought about it @Mte90 ? @ePascalC maybe?

Cheers,
Jb

**Comment by Mte90** [comment]
Browser extension support localization, I have to implement that but I think that will be a problem because GlotPress is not localized on translate.wordpress.org. So will be very badly for the user experience.

**Comment by fxbenard** [comment]
My 2 cents, rather I think GlotPress should be translated as well on translate.wordpress.org. Adding a zest of localization to your extension will not break any user experience with some intelligent comments not to translate the different actions

**Comment by Mte90** [comment]
As example in Mozilla we chosen to not translate tools with mixed part to avoid confusion and support request about a complete translation.

**Comment by Mte90** [comment]
I think that we have to see if GlotPress will support other languages on wordpress.org and in case implement something.

**Comment by audrasjb** [comment]
Since GlotPress is not going to be translatable, we are closing this issue as `wontfix` for now.
