### ISSUE TITLE
Fix codestyle errors

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#135]
check on https://app.codacy.com/app/mte90/GlotDict/issues/index?bid=3311070

**Comment by audrasjb** [comment]
Hi Daniele,
Good catch.
I guess we'll have to refresh the code to follow WP-JS Coding Standard too, but there is some work concerning this point 😊
https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/

**Comment by Mte90** [comment]
I think that we can try on trying the eslint rules of wordpress and see what happen in GlotDict.

**Comment by Mte90** [comment]
Already fixed
