### ISSUE TITLE
Shortcut Ctrl+Shift+F has two allocations

### ISSUE THREAD

**Issue by flashbash** [Mte90/GlotDict#136]
**Shortcut on _Ctrl+Shift+F_ to click "Fuzzy"**
Shortcut on Ctrl+Enter to click "Suggest new translation" or "Add translation"
Shortcut on Page Down to open the previous string to translate
Shortcut on Page Up to open the next string to translate
Shortcut on Ctrl+Shift+B to "Copy from original"
**Shortcut on _Ctrl+Shift+F_ to add non-breaking spaces near symbols**

**Comment by Mte90** [comment]
You are right, we didn't noticed that. @audrasjb what do you suggest as alternative for the non-breaking spaces as hotkey?

maybe Ctrl+Shift+N instead of Ctrl+Shift+F?

Ref: https://github.com/Mte90/GlotDict/blob/master/js/glotdict-hotkey.js#L55

**Comment by audrasjb** [comment]
Hey,
Yep, Ctrl+Shift+N seems good to me!

**Comment by audrasjb** [comment]
Hey @Mte90 
It seems like the issue fixed in https://github.com/Mte90/GlotDict/commit/8e8f4eaf74264bc08b6e763a13abc4aa7daec68b is still here.
![capture d ecran 2018-07-24 a 11 34 33](https://user-images.githubusercontent.com/1590998/43129857-93aed516-8f35-11e8-95b9-3daa9ce2f5a0.png)

**Comment by Mte90** [comment]
I think that I forgot to change the text on that part...
