### ISSUE TITLE
Bug: Don't render links in the Translation column

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#137]
Browser: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Link: https://translate.wordpress.org/projects/meta/wp15/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5863126&filters%5Btranslation_id%5D=54664989
Locale used: en_CA

Hi @Mte90 

I don't recall seeing this previously so might be a reversion or just the perfect circumstances, but now I'm seeing links being rendered in the Translation column and when the row is expanded. Screens below;
![screen shot 2018-04-03 at 9 36 34 am](https://user-images.githubusercontent.com/8726005/38262913-6960b884-3723-11e8-89fc-f5ad7f60d9c4.png)
![screen shot 2018-04-03 at 9 36 27 am](https://user-images.githubusercontent.com/8726005/38262912-6946e418-3723-11e8-8d89-6e6a5db90019.png)

I was going to log with GlotPress but checking with GlotDict disabled the issue goes away so appears to be isolated to the GlotDict extension.

Here's a sample string;
https://translate.wordpress.org/projects/meta/wp15/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5863126&filters%5Btranslation_id%5D=54664989

Appreciated,
Cheers

**Comment by Mte90** [comment]
If you disable the highlight spaces the issue disappear?
Probably the bug is on https://github.com/Mte90/GlotDict/blob/master/js/glotdict-functions.js#L188 where with that methoed the html will be rendered.

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 you hit the nail on the head there. Disabling that resolves the issue. 
So maybe the html needs to be encoded or escaped before adding the span for highlighting.

**Comment by Mte90** [comment]
I will check ASAP for a fix :-)

**Comment by Mte90** [comment]
After testing I cannot fix that, we inject a span so we need that html is rendered.
The only way is to integrate that support on glotpress side of the whole feature so there will be no problems.

**Comment by Mte90** [comment]
I saw that is possible to use .text, the issue is that we inject a span for highlight in the code and we need that this is rendered

**Comment by garrett-eclipse** [comment]
For sure, with PR #138 there I only use .html() which worked nicely to inject the highlight span while keeping the existing non-rendered HTML as escaped text. Give it a test so far it's satisfied all my cases
