### ISSUE TITLE
Some strings are not recognized due to the adiacent symbols

### ISSUE THREAD

**Issue by sgelob** [Mte90/GlotDict#14]
For example in the text **(in particular featured image).**

**featured image** is not recognized as tring due to the adjacent **).** and so is seen like a different string.

Can you make some filters or exceptions for this cases?

Thanks in advance ;)

**Comment by Mte90** [comment]
For that i have to improve the regular expression to detected this cases.
There is a page with this problem for testing?

**Comment by sgelob** [comment]
https://translate.wordpress.org/projects/wp-plugins/manual-image-crop/stable/it/default?page=3

Thank man! ;)

Same thing for the words starting by a capital letter, for example Upload and upload: https://translate.wordpress.org/projects/wp-plugins/manual-image-crop/dev-readme/it/default?page=2

**Comment by Mte90** [comment]
For the capital is very strange in some case this is not happening.

**Comment by Mte90** [comment]
fixed both the problem :-)
