### ISSUE TITLE
Feature Request - Add hotkey for dismissing warnings

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#141]
Hey @Mte90 
Just a thought, I think it would be very helpful to introduce a hotkey for dismissing warnings. This would especially be helpful with the glossary warning that GlotDict forces when you have a glossary string but have left it untranslated on purpose. This often comes up in en_CA as 'check' is in the glossary but is only valid for changing when it's talking about the monetary 'cheque' everywhere else it's left the same so I find at least 2-3 strings per page when translating with this warning slowing down the process quite a bit.
Thanks

**Comment by Mte90** [comment]
I am not sure if we can do it. I can disable the validation of GlotDict but not of GlotPress.
Maybe we can add an option that disable for the current page the validation.

**Comment by garrett-eclipse** [comment]
Sorry @Mte90 I think I didn't explain well enough. I wasn't asking to disable the validation, more just add a hotkey for dismissing the warning.

So when you submit a translation and there's a warning you can to click the 'Discard' link in the warning. But I found having to grab the mouse to click interrupts the flow so would be nice to have a Cmd+D (or something) which triggers a click on the first warning displayed in the open row. That way I can keep the flow of using only hotkeys and not need to grab my mouse every couple rows.

The warning w/ discard link I'm thinking would be nice to have a hotkey for dismissing is below;
![screen shot 2018-04-16 at 10 43 35 am](https://user-images.githubusercontent.com/8726005/38825977-42ee3880-4163-11e8-842c-e6d0087c817d.png)

I hope that is a bit more clear.
Thanks

**Comment by Mte90** [comment]
Got it!
I think that is possible to do it!
I will wait few days before to implement it (looking for ideas for a new major version) :-)

**Comment by garrett-eclipse** [comment]
Sounds good @Mte90

**Comment by garrett-eclipse** [comment]
Thanks @Mte90, I added PR #154 to expand this and encompass GlotPress warnings.
Testing it will only dismiss them when the row is open.
