### ISSUE TITLE
Feature Request - Bulk copy from original

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#142]
Locale used: English Variants

Hi @Mte90 I realize this is more useful for variant languages like en_CA, en_AU, etc. 
But am thinking a massive timesaver for those variant languages, and possible other variants when GlotPress updates to have language hierarchies, would be to have an additional option in the bulk dropdown for copying from the original. 
Currently to do this you open the row, then click 'Copy from original' and finally 'Add translation'. Then rinse and repeat for the next one.
This bulk option would enable you to copy 15 strings in two steps.

Hope that makes sense,
Cheers

**Comment by Mte90** [comment]
So you mean that all the translated terms are injected in the textarea?

I am wondering if it is the right behaviour. Right now in glotpress we are evaluating what to do for terms with more than 1 translation.
In any case seems that I can implement without so many problems.

The best probably is another link near copy from original with a text copy translated terms or something like that. Maybe with an hotkey :-)

**Comment by garrett-eclipse** [comment]
Sorry @Mte90 although that's a cool idea, wasn't what I was going for.

I'm thinking in this dropdown menu for bulk actions add a 'Copy' option like this;
![screen shot 2018-04-17 at 10 05 14 am](https://user-images.githubusercontent.com/8726005/38885160-df98a5ee-4226-11e8-9b12-97285c7d8b40.png)

And when you have rows checked off and you select this action it would copy the original string and submit it as the translation.
This only really helps in english variants where most strings have no adjustments needed so just get copied and submitted.

In my workflow I would scan the results and only check off those which don't have glossary terms and then I'm left with only strings that need attention.

Hope that clarifies.
Thanks

**Comment by Mte90** [comment]
Seems that can be interesting, maybe the auto insert and submit can have a check for translations where there only terms with a glossary to avoid bad subsmission of translation with incomplete stuff.

**Comment by garrett-eclipse** [comment]
Good call, maybe it would submit all rows without glossary terms but open those with terms and have a warning like the current behaviour for submitting a single string with untranslated glossary term.
