### ISSUE TITLE
Inject action buttons on load

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#146]
Browser: Chrome
Link: translate.wordpress.org
Locale used: en_CA

Hey @Mte90,

I'm not sure if this was there before the latest changes to translate.wordpress.org but it would be nice if the action buttons 'Reject', 'Fuzzy', 'Approve', etc. Are available on page load. Right now they only appear after you've submitted a row. It would be nice if you loaded up a table that holds translated, waiting, fuzzy strings that their actions were there on page load rather than on row submission.

Thanks

**Comment by Mte90** [comment]
This buttons are part of features that area available only on saving the new translation. 
So you are suggesting to save automatically a string with this status like rejected?

**Comment by garrett-eclipse** [comment]
Hi @Mte90 

No sorry, I meant on load have the buttons added to any rows that are already translated either in fuzzy, waiting or complete state. That way when you load up a project with waiting strings the buttons are already available.

Hope that clarified,
Thanks

**Comment by Mte90** [comment]
Probably you are right, https://github.com/Mte90/GlotDict/blob/master/js/glotdict-column.js is involved maybe the selectors are not valid anymore.

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 I'm looking at that but am a bit lost as I'm not sure how MutationObserver works. But looking through the rest the selectors seem right. Maybe you can take a look later and see if you can spot the difference. I'll return to this when I have some more time. Cheers

**Comment by Mte90** [comment]
![immagine](https://user-images.githubusercontent.com/403283/39782103-83fb12b6-5311-11e8-8bec-cde09939c129.png)
made a fix

**Comment by garrett-eclipse** [comment]
Thanks @Mte90
