### ISSUE TITLE
'Copy from original' broken on Rejected row

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#148]
Browser: Chrome Version 66.0.3359.181 on OSX Version 10.10.5
Link: translate.wordpress.org
Locale used: en_CA

I originally posted this as a GlotPress issue but have found it's only reproducible with GlotDict enabled so am assuming it's caused by GlotDict.

Details - https://github.com/GlotPress/GlotPress-WP/issues/908#issuecomment-394032850

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 
Retesting I found it's with the GlotDict reject/fuzzy actions that the issue occurs and the problem is the textarea loses it's id, reopening to investigate

**Comment by Mte90** [comment]
Can you explain the steps to replicate the issue?

**Comment by garrett-eclipse** [comment]
For sure, and I think I have it isolated so will push a fix for this.

But the issue isn't with the existing Meta actions;
<img width="384" alt="screen shot 2018-07-05 at 1 02 15 am" src="https://user-images.githubusercontent.com/8726005/42310066-5176fcb4-7fef-11e8-9770-ab6cc4928d47.png">


Rather it's with the ones injected by GlotDict found on the right side when the row is closed;
<img width="174" alt="screen shot 2018-07-05 at 1 02 21 am" src="https://user-images.githubusercontent.com/8726005/42310079-582e1164-7fef-11e8-8a75-34846d0ef779.png">

When these are used the row somehow loses the id found on each textarea which is used in the Copy function.

In the console you'll see this error after you try to 'Copy from original' after you've rejected a row;
Uncaught TypeError: Cannot read property 'split' of undefined
at Object.copy (editor.min.js:1)
at HTMLAnchorElement.copy (editor.min.js:1)
at HTMLTableElement.dispatch (jquery.js:3)
at HTMLTableElement.r.handle (jquery.js:3)

Cracking open the file it's for this line in the copy action;
var e = d.parents(".textareas").find("textarea").attr("id").split("_");

**Comment by garrett-eclipse** [comment]
Hey @Mte90 

I isolated the problem to the custom gd_set_status function as it was replacing the rows but wasn't applying all needed classes. 

While delving I found GlotPress provides the majority of this functionality so I latched into their functions to address this and in the process cleaned up the code.

Let me know what you think
