### ISSUE TITLE
Feature Request - display language depending warnings

### ISSUE THREAD

**Issue by fwilly** [Mte90/GlotDict#149]
Browser: *
Link: *
Locale used: de_DE or de_DE (Formal)

The German translation style guide define requirements. **Is it possible to highlight specific parts with a background color?**

Example:
1. In German the quotes "word" should be translated into „Wort”. => quotes (not upper or lower quoting marks) should be highlighted.
2. "z.B." or "z. B." should be replaced to "z.&nbsp;B." => highlight failing forms
3. "Du" or "Deine" => "du" or "deine" => highlight failing forms

Better would be a possibility to define such failing translated forms in depending to a locale.

**Comment by Mte90** [comment]
Seems an interesting idea but not easy to implement for locale.
I need a list of this words and add that as an option to enable in the extension.

**Comment by audrasjb** [comment]
Hi @fwilly and thank you for your request.

Concerning item 1) I guess we can add an optional checkbox as we already have an optional checkbox for curly quotes. I can work on this enhancement. Also, some other locales could benefits of an option concerning quotes. 
I'm afraid items 2) and 3) are too specific and very difficult to implement… but @fwilly concerning Du/Deine => du/deine, you can use your locale glossary to implement hints for translators :)

Cheers,
Jb

**Comment by Mte90** [comment]
Add another validator is not a problem for case 1, for the other 2 cases they are too much language based and not easy to implement.

Let's see the first case in the meantime :-)

**Comment by audrasjb** [comment]
Thanks for your confirmation :)
Let’s jump into item 1! :D

**Comment by audrasjb** [comment]
@fwilly #151 fixed item 1.
Glotdict can't handle other items (see above discussion).
