### ISSUE TITLE
Suggestion: group all the tools in one place

### ISSUE THREAD

**Issue by fr-laurentn** [Mte90/GlotDict#150]
Hi @Mte90 

Thanks for your great work. 

I have a suggestion to improve the user experience.

When you install GlotPress, it adds various tools to the screen. 

Some are at the top of the page (ex: the review button), some are at the bottom (ex: the locale selector). 
It is not easy when you install the extension for the first time to understand where is what and what you have to do.

I think it will be easier for users if you could group everything in one place.

Let me know if I'm not clear.

**Comment by Mte90** [comment]
Hi and thanks :-D

Yes is missing a tour or something that explain how to use glotdict. My idea was to do a video about it because I have no idea right now how I can improve the UI.

If I can find someone that can help on that I am happy to improve the UX of GlotDict/GlotPress.

**Comment by Mte90** [comment]
close in favour of #103
