### ISSUE TITLE
Can someone design the icon for this extension?

### ISSUE THREAD

**Issue by sgelob** [Mte90/GlotDict#16]
;)

**Comment by CrowdedTent** [comment]
Proposal uno.

![glotdict-extension-logo-proposal-i](https://cloud.githubusercontent.com/assets/3118563/14801623/68d56e76-0b53-11e6-97d0-c9907e3a14d1.png)

**Comment by CrowdedTent** [comment]
Proposal due.

![glotdict-extension-logo-proposal-ii](https://cloud.githubusercontent.com/assets/3118563/14801630/7775e47e-0b53-11e6-9df3-12dc1c4a9a77.png)

**Comment by CrowdedTent** [comment]
Vector template.

[GlotDict-extension-logo-proposal-template.pdf](https://github.com/Mte90/GlotDict/files/235566/GlotDict-extension-logo-proposal-template.pdf)

**Comment by Mte90** [comment]
Today I publish on the store the new version with that icon :-D

**Comment by sgelob** [comment]
Thank you guys! ;)

**Comment by CrowdedTent** [comment]
Awesome, thank you! :-D
