### ISSUE TITLE
Missing "important" languages

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#166]
It was pointed out that we're missing several languages that are supported on translate.wp.org;
> More "important" languages are missed, for example: bal (catalan baleari) - ca (catalan) - de_CH - en_NZ - en_ZA - es_AR - es_CL - es_CO - es_CR - es_GT - MX - es_US - es_PE - fr_BE - fr_CA - pirate (english pirate) :wink:

GlotDict 'Pick locale' selector;
<img width="165" alt="screen shot 2018-07-10 at 10 20 37 pm" src="https://user-images.githubusercontent.com/8726005/42552122-bd4fe000-848f-11e8-9241-0f7725d65d81.png">
Powered by gd_locales - https://github.com/Mte90/GlotDict/blob/a472c5ae13d806802da28805a5d1a9a614f7ba61/js/glotdict-functions.js#L55

translate.wp.org Languages;
![locales glotpress wordpress](https://user-images.githubusercontent.com/8726005/42552141-d0f81a46-848f-11e8-8400-875d0cb893ce.png)
These locales are defined here - https://github.com/GlotPress/GlotPress-WP/blob/43bb5383e114835b09fc47c727d06e6d3ca8114e/locales/locales.php#L101

And then there's the login locale selector which is powered via the wporg_locales database;
https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-login/functions.php?rev=7265#L160

I wasn't able to find any ajax endpoints or javascript objects holding the GP list so for GD would need to be updated manually.

**Comment by Mte90** [comment]
For that I am using https://github.com/Mte90/GlotDictjson that I update when a new glossary is enabled for a locale. Later glotdict everyday do a call to the server that everyday check the list and update the file and in case is new compared to the local version this list is updated.
Actually we need the settings for locales to be able to auto add the link to the glossary and not for other reasons.
So add languages that are not available doesn't have now any sense.

So for me is wontfix or if someone can add more idea how to use that.
