### ISSUE TITLE
[bug] "Approve" shortcut is broken

### ISSUE THREAD

**Issue by audrasjb** [Mte90/GlotDict#167]
Browser: Chrome
Link: See animation below
Locale used: fr_FR

"Approve" shortcut seems to be broken. My browser inspector reports an error in glotdict-columns.js, L.14.

![glotdict-bug](https://user-images.githubusercontent.com/1590998/42562091-1d127118-84fb-11e8-94d2-b2286b07572d.gif)

**Comment by Mte90** [comment]
So the button with issues is the added in the column because the internal are working.

**Comment by garrett-eclipse** [comment]
Thanks for fixing that, sorry copy pasting issue I introduced
