### ISSUE TITLE
Issue with the new width

### ISSUE THREAD

**Issue by fr-laurentn** [Mte90/GlotDict#168]
Browser: Firefox 61.0.1
Link: anywhere on https://translate.wordpress.org
Locale used: any locale

Hello, 

First, thanks a lot for the work on the new release! It's awesome.

Among the new features, you changed the width of the view to 85%.

It might be a good idea on small screens but on a very large screen, it is not very user friendly.

My resolution: 1920*1980
Find attached to this issue some screenshots.

Is it possible to improve this feature? (or to make it optional?)

Thanks in advance,

**Comment by fr-laurentn** [comment]
![screenshot2](https://user-images.githubusercontent.com/15927630/42569209-0ed0377e-8510-11e8-9b99-6e2ebff20f2a.png)
![screenshot1](https://user-images.githubusercontent.com/15927630/42569213-10dea9ec-8510-11e8-9e0c-a65c429b4b72.png)

**Comment by Mte90** [comment]
We can work to do that change only on the listing of strings because there is very comfortable. We can see for a minor!
