### ISSUE TITLE
BUG: Translated String count should be present on untranslated rows

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#169]
Hmms seems I didn't hit the nail on the head here either but with untranslated rows I'd tried to suppress the Translated String info but it's visible and to boot the word count isn't 0 there.
![screen shot 2018-07-11 at 2 36 17 pm](https://user-images.githubusercontent.com/8726005/42600662-05f28ae6-8518-11e8-900e-fab10f0a0fd6.png)

Another minor nuance is the word count for Current String when textarea is empty should be 0 but is displaying 1.

**Comment by claudiobrandt** [comment]
With a translated string present, the Translated String counter seems to be carrying the number of words from the Original String (in the image below, the OS has 12 words). The number of characters, though, is correct. In the image, the Translated String is the same as the Current String, with 14 words:

![glotdict-counter-bug](https://user-images.githubusercontent.com/30415322/43165847-5160364c-8f6b-11e8-9b8e-da34ab7dad92.PNG)

**Comment by garrett-eclipse** [comment]
Thanks @claudiobrandt, I'll try and get a patch out shortly to address this.
