### ISSUE TITLE
Change 'Review in progress' label

### ISSUE THREAD

**Issue by fr-laurentn** [Mte90/GlotDict#173]
Browser: Not browser related
Link: <where happen the issue>
Locale used: all

Hi,
The label 'Review in progress' is quite confusing since it implies that the review is still processing but I get error messages, so I guess the review is finished. 

And since the message never changes, new user think something is broken and don't understand what to do.

Would it be possible to change it to something clearer? I've been using GlotDict for a while now and I'm still not sure what it's supposed to mean :)

Thanks

**Comment by Mte90** [comment]
The label text is changed when the Review button is pressed https://github.com/Mte90/GlotDict/blob/99e1211ae93e00f8ea83d0b49801c9000edcc002/js/glotdict.js#L77

For the extension is not easy to understand when the task is finished but I can understand the doubts.
Maybe we can find a better text to say that the automatic validation review was executed.

**Comment by garrett-eclipse** [comment]
@Mte90 do we know when the process is complete and all items marked?
It might be a good approach to have the text change to 'Review in progress' when the action is started. Then when all items have been flagged with the red line and the process is complete it can state 'Review complete (XX Items Found)' or if we want to be clearer 'Review complete (XX Items Flagged in Red)' or 'Review complete (XX Items Flagged Below)'
Just thought it might be nice to indicate the number of items flagged especially if it's 0 as you can then just move on or if it's greater than 0 you know you have items to address.

**Comment by Mte90** [comment]
The only way to know if the review is finished is to check if all the alerts are dismissed but I think that to check we need a timeout or to append an event in a lot of actions.

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 
I feel we're on different pages there. 

Looking at the action I feel the review completes once the action completes and all rows have been flagged with warnings. But sounds like you're viewing it as when the user has actually gone through and cleared all the warnings.

I think from a UX perspective the tools review is complete once all rows are flagged so the button can update at that point to indicate it's process is complete and possibly indicate the number of warnings or affected rows.

This is slightly different from the users actual review which involves them handling all the warnings that have been flagged.

In my opinion these are two separate but complementary processes. One that the tool conducts and the other that the user conducts. And I feel my and @fr-laurentn confusion is that when the tool has completed the gd_run_review process it has no more action to take so should indicate it's finished/complete. By leaving it stating 'Review in progress' users feel they need to wait for that process to complete before they take action.

So with that in mind looking at the code I feel the gd_run_review can be updated to count either warnings or affected rows and return that;
https://github.com/Mte90/GlotDict/blob/a472c5ae13d806802da28805a5d1a9a614f7ba61/js/glotdict-validation.js#L6-L17
And then using that information the .gd-review click action can update the button value after gd_run_review() is executed to indicate 'Review is complete/finished, there's X warnings (or X rows affected)'. We can probably also then disable the button as you won't need to click again, and by disabling then there's no need for the .gd-review-done click alert as you won't be able to trigger it anyway.

Let me know what you think and I can work on a PR.
Cheers

**Comment by Mte90** [comment]
I think yes this will be the best way but maybe need a little bit of code organization improvement :-)

**Comment by fr-laurentn** [comment]
Hi @garrett-eclipse 

Thanks for jumping in, that's exactly what I meant.

I never understood that 'Review in progress' meant that 'my' review is in progress. It makes more sens to me now, but I agree it would be great if it could be changed to 'Review completed' or something like that.

However, since I'm not a developer I have no idea what it takes to develop that and I can't help you ^^

**Comment by garrett-eclipse** [comment]
Fixed in #198

**Comment by fr-laurentn** [comment]
Thanks for taking my suggestion into account !

**Comment by fr-laurentn** [comment]
Just noticed the new "review complete" button. Thank you very much, that's really great!
