### ISSUE TITLE
Validation warning for dot dot dot still flagged when replaced with ellipsis character '…'

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#174]
Browser: Chrome
Link: https://translate.wordpress.org/projects/wp-plugins/wp-migrate-db/dev/en-ca/default?filters%5Boriginal_id%5D=750523
Locale used: en_CA

The warning for final '...' triggers on the original and not the currently submitted translation as replacing an instance of '...' (dot dot dot) with the ellipsis character '…' still triggers the warning.

If the intent of the feature is to also prompt the replacement of the ellipsis character '…' with the &hellip; code the logic needs to be updated to intercept this.

Validation Code;
https://github.com/Mte90/GlotDict/blob/a472c5ae13d806802da28805a5d1a9a614f7ba61/js/glotdict-validation.js#L91-L105

So to determine the appropriate path forward there's two questions on the functionality intent;
1. Should the ellipsis be treated like the dot dot dot and trigger the validation warning which prompts to replace with '`&hellip;`'?
2. If the dot dot dot is removed or replaced with something other than `&hellip;` should the warning still be triggered?

Thanks

**Comment by garrett-eclipse** [comment]
Hey @Mte90 sorry for the confusion.

Currently if the string ends in an ellipsis instead of three seperate periods then the validation isn't run, so I'm wondering if it's preferred to have &hellip; in place of the ellipsis character?
Also if you did have three periods and triggered the warnings, if you remove them the warning will persist or if you replace with the ellipsis character the warning persists as the warning checks the original string and not the current one.

Mostly what I'm unclear on is how the ellipsis character should be handled. Should we care when it's present and trigger the warning?

Thanks

**Comment by Mte90** [comment]
I think that we can handle both the cases and to suggest to use the hellipses character for every case.

**Comment by garrett-eclipse** [comment]
Sounds good, and should we cover any cases where it's not at the end of the string? For instance if it's a multi-line paragraph with a middle sentence ending in ... should we also intercept those?

**Comment by Mte90** [comment]
I think that is better only at the end of the string to avoid confusions.
