### ISSUE TITLE
Hotkey to force submission without validation

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#178]
This is a feature proposal to add a new keybinding for force submission which would skip validation.
Was thinking Ctrl+Shift+Enter as the keybinding since Ctrl+Enter is the standard submission keybinding.
This feature would be beneficial when you're aware of a false-positive Glossary term so rather than have to submit, clear warnings and resubmit you'd be able to force the submission.
In English variants this is very helpful as we have 'check' as a glossary term but it's only valid when it's in reference to the monetary cheque. If you're aware it's present in the string this feature would be nice to streamline the workflow.

When I have a chance will take a stab with a PR

**Comment by Mte90** [comment]
We can do that but I think that we have to keep the validation of GlotPress to avoid issues with the data saved in GlotPress but we can ignore the validation of GlotDict.

**Comment by garrett-eclipse** [comment]
Agreed, the GlotPress warnings come after submission so they're less intrusive and can be ignored whereas the GlotDict ones block submission which is the frustration I'm hoping to overcome.

**Comment by garrett-eclipse** [comment]
Implemented in #199
