### ISSUE TITLE
While checking strings you want the number of them

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#179]
It is a feature request that we need to choose where show that number.

**Comment by khoipro** [comment]
![screenshot at sep 07 17-10-24](https://user-images.githubusercontent.com/10395311/45213414-a74be000-b2c1-11e8-82f2-231b3e79997c.png)

I attached a screenshot about the count of approved/rejected strings should be displayed after a PTE/GTE clicked a bulk check button.

**Comment by khoipro** [comment]
I have two cases need to improve.

1. When I made a bulk approve/reject strings, but during selection, I still fix a few strings (manual). A counting is needed to keep we make a stat better.  For example, we wish to know how many strings were bulk approve one-time.

2. We know we can compare a number of untranslated strings before and after approving, but that's better to keep displaying a confirmation about this number in top to keep us working more to complete them as soon as possible.

Thanks and hope to see an improvement soon.

Regard,
Khoi Nguyen
@khoipro GTE - Vietnamese

**Comment by garrett-eclipse** [comment]
Is this not already the case when you bulk approve?

Selecting a couple of waiting strings and approving them via the Bulk Actions you should get a notice above the breadcrumbs;
![screen shot 2018-09-07 at 9 09 23 am](https://user-images.githubusercontent.com/8726005/45230505-e6584200-b27d-11e8-9b7f-66525d409d12.png)

Or am I missing the mark?

**Comment by Mte90** [comment]
The idea was to show without press the button but somewhere in the ui the actual number of selected elements.

**Comment by garrett-eclipse** [comment]
Are you sure? 
The request indicates after button click;
'I attached a screenshot about the count of approved/rejected strings should be displayed after a PTE/GTE clicked a bulk check button.'
So wouldn't the current behaviour suffice displaying the number of translations affected but the bulk action?

**Comment by Mte90** [comment]
As I understood was before the press of the click to understand the status of strings in progress

**Comment by khoipro** [comment]
1. First Case: I wish to select a few items (and on the top, it displays a total selected number in real-time). It wasn't submitted.
2. Second Case: After approving bulk strings, I wish to display a number of approved/rejected strings. It was submitted using a button.

**Comment by khoipro** [comment]
<img width="482" alt="screenshot at sep 09 11-41-51" src="https://user-images.githubusercontent.com/10395311/45261160-65d44580-b425-11e8-9b99-fb635a5eaaf7.png">

I made a screenshot of the real-time update number of strings were selected to make it visualize.

**Comment by khoipro** [comment]
I think this one is great and I think it's ok.

https://user-images.githubusercontent.com/8726005/45230505-e6584200-b27d-11e8-9b7f-66525d409d12.png

So we just focus to have a "real-time" update total of selected strings.

**Comment by khoipro** [comment]
Hi,

I also found a bug and wish to add a counter when we are using a specific filter like that, for example, filter by username. A total showing string is not available.

The current user don't translate all 198 strings, so it's a wrong number displayed. I guest it will be on same case, but don't need to be a real-time.

![screenshot at sep 10 08-52-12](https://user-images.githubusercontent.com/10395311/45272369-02a2eb80-b4d7-11e8-86fd-e5217e96de28.png)

**Comment by khoipro** [comment]
You can check here.
https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/dev/vi/default?filters%5Bterm%5D=&filters%5Buser_login%5D=zztalano1zz&filters%5Bstatus%5D=waiting&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

User to test is: "zztalano1zz"

**Comment by garrett-eclipse** [comment]
Hi @khoipro 

I setup PR #187 to add the new notices as can be seen here;
![screen shot 2018-09-11 at 4 23 34 pm](https://user-images.githubusercontent.com/8726005/45393639-babcbb00-b5e1-11e8-9281-7fb5655c391e.png)

Take a look and you can test by taking the contents of the new glotdict-notices.js found on that PR/branch and dump into your js console. Also for the colours just add the new css in via inspect. 

Let me know if you have any thoughts or change request.
Cheers
