### ISSUE TITLE
Validation of glossary terms with multiple translations

### ISSUE THREAD

**Issue by ajoah** [Mte90/GlotDict#188]
I noticed that sometimes there are several possible translations for one term. For example in french `new` could be translated by `nouveau` (male) or `nouvelle` (female).
I noticed too that locales use generally `/` to separate the different solutions.

Currently, GlotDict validate these translations globally like this : 

![image](https://user-images.githubusercontent.com/10757301/45537946-efa95780-b805-11e8-9222-1f3d94996634.png)

The translation is correct but there is an alert.

A solution would be to split the translations by the separator `/` and check each translation term independently.
This option would be activated in the glotdict settings. Some locales use `/` to separate endings like german so it could be strange if it is activated by default : 
![image](https://user-images.githubusercontent.com/10757301/45538785-49128600-b808-11e8-9023-1760a6da0590.png)

What do you think ?

**Comment by Mte90** [comment]
This mean to implement a parsers of terms because in italian glossary as example we don't use / we add every instance of a term.

**Comment by ajoah** [comment]
I'm not sure I understand. For example for `about` you are using `/` no ? https://translate.wordpress.org/locale/it/default/glossary

**Comment by Mte90** [comment]
yes we are using it but there are cases when we have "chi siamo/sono o Info" that mean "about/who are or info" so the rule of slash is not always following that scheme.
Anyway we can think to add an option to enable the parse so we can avoid languages that not use that scheme.

**Comment by ajoah** [comment]
The parser will be very simple, I was just thinking of split the string on `/`. For the italian, only `about` it problematic no ? I could be easily replaced by `about/who are/info`. There is`N/A` too but we can add an exception to ignore it.

**Comment by Mte90** [comment]
Yes exactly we can write a little guide on the wiki explaining that and we can avoid the option too

**Comment by garrett-eclipse** [comment]
@ajoah Would providing two separate glossary entries for the two terms for the male/female versions resolve your issue?

Using Italian as an example 'Activate' has two possible translations;
![screen shot 2018-09-17 at 4 26 04 pm](https://user-images.githubusercontent.com/8726005/45655708-76746380-ba96-11e8-9034-6156c1d60a18.png)
Reference - https://translate.wordpress.org/locale/it/default/glossary

If you don't provide either of the translations then you get the warning with both terms comma separated;
![screen shot 2018-09-17 at 4 27 37 pm](https://user-images.githubusercontent.com/8726005/45655740-9e63c700-ba96-11e8-9c1d-14fbf97371e9.png)
Example I'm using -  https://translate.wordpress.org/projects/wp-plugins/activate-update-services/dev-readme/it/default?filters%5Boriginal_id%5D=2859372

But if you provide one of the variations then you won't get a warning.

So I may be wrong but if you replaced your entry for nouveau/nouvelle with two separate entries does that not solve your issue as it won't give you the warning if one or the other is used, but will if neither are used...

**Comment by garrett-eclipse** [comment]
Hahaha I didn't even realize my example of activate was just a bogus duplicate. @Mte90 you'll want to remove that duplicate from the IT Glossary.

But with that example I guess 'Update' is a better term as it actually has two separate translations and can be a noun;
![screen shot 2018-09-18 at 9 29 45 am](https://user-images.githubusercontent.com/8726005/45702015-8c7d3500-bb25-11e8-852d-55855e829c96.png)

And to assist in clarity for translators you can provide comments on your Glossary terms which will show in the tooltip. I use that to indicate when to use a term or you can use it to indicate how to differentiate between the two variants.

**Comment by ajoah** [comment]
Just to be sure i understood your solution : it is to duplicate row for each solution like this ? 
![image](https://user-images.githubusercontent.com/10757301/45746401-7cd41e00-bc03-11e8-9e66-ace68cf9faf7.png)

**Comment by garrett-eclipse** [comment]
Hi @ajoah, yes exactly.

By having each possible translation of a term as it's own unique Glossary term you can then also provide comments on it to indicate in which context to use each version. You almost have that already with New|noun|Nouveauté|Readme and would just split Nouveau/Nouvelle into two separate entries.

The tooltip for the term will list each entry separately along with it's comment so at a glance you can tell which version should be used.
![screen shot 2018-09-19 at 9 50 37 am](https://user-images.githubusercontent.com/8726005/45768502-f236f300-bbf1-11e8-9f06-be6800e73775.png)

And the warning logic is setup so it will only flag if there's no match, if you did use one of the term replacements then no warning would be triggered. Also on the warning each possible term is comma separated.

Let us know how that works for you and if all good we can close this up and avoid any parsing logic.

**Comment by ajoah** [comment]
Ok, so i have discussed it with my locale team (french) and they are not very keen for this solution. @audrasjb neither, I let you talk about it :)

**Comment by garrett-eclipse** [comment]
Thanks @ajoah sorry for the delay was away for some holidays after discussing with @audrasjb so am just getting around to updating this.

I'm closing this as a `wontfix` to avoid introducing a convention in GlotDict that would negatively affect non-GlotDict users, along with the fact the GlotPress system already handles multiple translations nicely if entered as unique glossary entries.

To assist the Polyglots I started a Make/Polyglots _doing_it_wrong post to flag this potential issue to Glossary editors and guide them to creating unique entries per translation as GP is 1-to-1 and will stay that way.

I would love you input/feedback on the post as I'm hoping to clean it up before posting next week.   
https://github.com/Mte90/GlotDict/wiki/Glossary-Entries-should-be-1-to-1-(%60_doing_it_wrong%60)

I also noted that the GlotDict warning doesn't account for plural in it's verbiage well so opened #201 to address that.

As well to assist flagging to Glossary editors that they should have each translation as a unique entry I created #202 to suggest the creation of a notice and warning on the glossary page.

**Comment by ajoah** [comment]
Hi @garrett-eclipse,
Sorry but i don't know if we are talking about the same thing.
In your exemple https://github.com/Mte90/GlotDict/wiki/Glossary-Entries-should-be-1-to-1-(%60_doing_it_wrong%60) there are a translation for a verb and for a noun. Glossary managers have to already separate these translations because it is not the same "part of speech". 

But how to when for a single english noun, there are multiple possible nouns as translation ?

I repeat my french example with "new".

It could be translatable to 
- "Nouveauté" (verb) 
- "Nouvel", "Nouveau", "Nouvelle" (adjectives)

So, for the adjectives Glossary managers have to use random "part of speech" ? (because we cannot use same word and same "part of speech" twice.)

**Comment by ajoah** [comment]
> because we cannot use same word and same "part of speech" twice.
Ok you have make a PR to GlotPress to remove this check : https://github.com/GlotPress/GlotPress-WP/pull/947

It is perfect for me 👍

**Comment by garrett-eclipse** [comment]
Hi @ajoah sorry for the initial stumble there the restriction on 'part of speech' came in 2.4 but will be removed in 3.0 as you found in that PR. Once that's live on translate.wp.org I'll update this thread and finally get that make/polyglots post out.
