### ISSUE TITLE
Current String count 0 after 'Copy from Original'

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#191]
If you use the new Bulk Action for 'Copy from Original' and open a row the Current String count will be 0 briefly before the js updates it. The counts there should be updated as part of the 'Copy from Original' action.

**Comment by tarunjindal790** [comment]
Hello @garrett-eclipse ,Sorry I am new in the open source world and can't get my head around some of the stuff.Can you guide me on how can I find the related file for this issue?

**Comment by Mte90** [comment]
You need to have a WordPress.org account, go to translate.wordpress.org and try to localize.
We have also a guide on how to get a test environment https://github.com/Mte90/GlotDict/wiki/Test-extension-locally
The file is https://github.com/Mte90/GlotDict/blob/master/js/glotdict-notices.js

**Comment by tarunjindal790** [comment]
Thanks for the reply.Working on the issue.

**Comment by garrett-eclipse** [comment]
Closing as resolved in #210
