### ISSUE TITLE
'Copy from Original' carries context string into the textarea

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#192]
The new 'Copy from Original' bulk action code found here;
https://github.com/Mte90/GlotDict/blob/master/js/glotdict-bulk.js

Doesn't take into account the .context string which is a span found within the .original div;
For instance;
```
<td class="original">
		Scheduled Actions				<span class="context bubble" title="Context: Admin menu name">Admin menu name</span>
		
	</td>
```
![screen shot 2018-09-26 at 11 22 44 am](https://user-images.githubusercontent.com/8726005/46100732-f5e0f180-c17e-11e8-882c-a991caf986c8.png)

This causes the context to be added to the translation. So we'll have to strip the span within the action.

**Comment by Mte90** [comment]
Yes that span need to be removed on the count by the exntesion, not in the page.
