### ISSUE TITLE
The new width doesn't work on all projects

### ISSUE THREAD

**Issue by ajoah** [Mte90/GlotDict#219]
Browser: Firefox 63.0.3
Link: any project on https://translate.wordpress.org when you don't have PTE rights (no bulk actions menu)
Locale used: any locale

Hi, 
I think the commit https://github.com/Mte90/GlotDict/commit/99e1211ae93e00f8ea83d0b49801c9000edcc002 has created a bug.

Indeed, the `#bulk-actions-toolbar-top` is only present when we have PTE rights. So when we want to suggest a translation on a project where we don't have PTE privileges, we get the old small width.

Maybe, we can replace this css ID by `#upper-filters-toolbar` which is present all the time.

**Comment by Mte90** [comment]
can you share a screen of the problem?

**Comment by Mte90** [comment]
Tested and now is fixed, we will see if release a new version with only this bugfix or wait for other stuff :-)

**Comment by ajoah** [comment]
Thanks for your responsiveness :)
