### ISSUE TITLE
Suppress the 'Scroll to xx_XX' on the new Top 100 pages.

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#222]
With the introduction of new Locale Stats pages on translate.wp.org I found the 'Scroll to xx_XX' evident on these pages but it's not useful as the table is project based and not locale based so should be suppressed.

The pages;
Top 100 Plugins https://translate.wordpress.org/locale/pt/default/stats/plugins
Top 100 Themes https://translate.wordpress.org/locale/pt/default/stats/themes

My original Meta Trac ticket - https://meta.trac.wordpress.org/ticket/4193

Screens;
<img width="958" alt="screen shot 2019-02-20 at 2 00 13 pm" src="https://user-images.githubusercontent.com/8726005/53128410-a0d0be00-3519-11e9-9bdf-ced8bec2a316.png">
<img width="952" alt="screen shot 2019-02-20 at 2 00 08 pm" src="https://user-images.githubusercontent.com/8726005/53128411-a1695480-3519-11e9-8cc8-427b8485402b.png">

Cheers

**Comment by Mte90** [comment]
This was made for https://translate.wordpress.org/stats/ and the check was by title and not url and these page have the same title.
Fixed :-)

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 those buttons are now gone. Appreciated.
