### ISSUE TITLE
Add 'Scroll to xx_XX' to individual Project pages

### ISSUE THREAD

**Issue by garretthyder** [Mte90/GlotDict#223]
I really liked the 'Scroll to xx_XX' button found on the `Translation status overview` page here;
https://translate.wordpress.org/stats

It would be helpful to reuse this functionality on individual project pages so users can use it instead of Ctrl+F/Cmd+F to find their locale.

Plugin Project - https://translate.wordpress.org/projects/wp-plugins/classic-editor
Theme Project - https://translate.wordpress.org/projects/wp-themes/twentyseventeen

**Comment by webaxones** [comment]
Closing this issue as it was fixed in #261
