### ISSUE TITLE
<Theme/Plugin Name> Projects to Translate links go to Page not Found

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#224]
On the Plugin/Theme i18n project pages there's a link at the top right labelled '<Theme/Plugin Name> Projects to Translate' which leads to a 'Page not found' screen.

Steps to reproduce;
Navigate to any project page (Ex. https://translate.wordpress.org/projects/wp-plugins/classic-editor)
Click the link top right that says '<Name> Projects to Translate'
You'll find yourself on a 404

The link on plugins goes to https://translate.wordpress.org/locale/wp-plugins/default
The link on themes goes to https://translate.wordpress.org/locale/wp-themes/default

I believe this link can be removed as the projects are listed below on those pages.

Moved from Meta Trac - https://meta.trac.wordpress.org/ticket/4194

**Comment by Mte90** [comment]
someone reported me another but https://meta.trac.wordpress.org/ticket/4316
I will work on that to get a fix asap

**Comment by Mte90** [comment]
There is people that use this link, I fixed the url generated right now :-)

**Comment by garrett-eclipse** [comment]
This still leads to a Not Found page using GlotDict 1.5.2, the URL hasn't changed.

**Comment by Mte90** [comment]
I am getting the right url on page about strings but not on https://translate.wordpress.org/projects/wp-plugins/classic-editor/ and in this page is not useful.

**Comment by garrett-eclipse** [comment]
Thanks @Mte90
