### ISSUE TITLE
Uppercase warning is not necessary for some locales

### ISSUE THREAD

**Issue by naokomc** [Mte90/GlotDict#225]
Locale used: ja
I started seeing "missing an initial uppercase letter" warning just today.
This is not relevant for some locales such as Japanese since the characters don't have upper/lower cases.

![image](https://user-images.githubusercontent.com/34067/57079884-47acb400-6d2c-11e9-9cab-40a511d91db5.png)

https://en.wikipedia.org/wiki/Capitalization

**Comment by Mte90** [comment]
There is an option in glotdict to disable this feature :-)
