### ISSUE TITLE
Plural strings in new interface cause error which places the gd-loader over screen

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#227]
With the new interface the plurals selectors are changed, this causes an error which leaves the gd-loader over the screen;
<img width="957" alt="Screen Shot 2019-05-11 at 3 20 19 AM" src="https://user-images.githubusercontent.com/8726005/57568407-dc9e5580-739b-11e9-8f59-df256a4ed3d7.png">

**Comment by Mte90** [comment]
I am releasing a new version that should fix that problem but I don't have any page to test a plural string.

**Comment by garrett-eclipse** [comment]
Hi @Mte90 here's some strings to test this.

Arabic - Multi-Plural Form - https://translate.wordpress.org/projects/wp/dev/ar/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7578389&filters%5Btranslation_id%5D=62869302
*This link shows the issue with the overlaying loader.

Canadian - Single-Plural Form - https://translate.wordpress.org/projects/wp/dev/en-ca/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7578389&filters%5Btranslation_id%5D=62866274
*This link shows the single plural form which doesn't have this issue. 

It's just the multi-plural as the textareas setup and how the numbers associated are handled now changed their selectors.

Cheers
