### ISSUE TITLE
Incorrect glossary for sk_SK, they use Gdoc, not the standard one

### ISSUE THREAD

**Issue by ePascalC** [Mte90/GlotDict#23]
Proprosal to remove until I / we find a way to convert the Gdoc ...

**Comment by Mte90** [comment]
Ref: https://github.com/Mte90/GlotDict/pull/18

**Comment by Mte90** [comment]
@Angelo-Verona I am working on the new version of glotdictjson (https://github.com/Mte90/GlotDictJSON/tree/webscript) that download automatically from glotpress.
So if your community don't update the glossary on glotdict i had to remove that locale.
