### ISSUE TITLE
Add list of talks about GlotDict in the readme

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#232]
To improve the knowledge about the extension is not bad add list of talks in the readme.

- https://wordpress.tv/2017/04/29/glotdict-pte-bot-and-bulkrejectgp-why-your-community-needs-a-glossary/
- https://wordpress.tv/2016/05/31/daniele-scasciafratte-glotdict-how-a-browser-extension-changes-your-translation-workflow/

And the new one by @garrett-eclipse when will be published :-D
https://docs.google.com/presentation/d/1MiJNsbv1oIIlq5tj1P-lkc5y_F4JO3mFVNwk45XevtU/present

**Comment by garrett-eclipse** [comment]
Good call @Mte90 my talk will be posted to wordpress.tv by next week so when it's made available I'll submit a PR to include it.
Cheers
