### ISSUE TITLE
Adding fr-CA to the Glossary

### ISSUE THREAD

**Issue by maximejobin** [Mte90/GlotDict#235]
I couldn't find fr_CA in the glossary list as you can see here:

![image](https://user-images.githubusercontent.com/1080760/58820910-e06f7180-8601-11e9-8d07-d1301dd235e9.png)

Then, I've seen this:
[Glossary Entries should be 1 to 1 (`_doing_it_wrong`)](https://github.com/Mte90/GlotDict/wiki/Glossary-Entries-should-be-1-to-1-(%60_doing_it_wrong%60))

So I've update our glossary... but what's next?

It says to ping @audrasjb or @garrett-eclipse but maybe the list will automatically update itself later?

**Comment by Mte90** [comment]
I have added it the other day to glotdict using the server, so let's wait tomorrow :-D

**Comment by maximejobin** [comment]
I still don't see it.

**Comment by Mte90** [comment]
there was an issue with the server, now is fixed.
You have to wait for your browser cache(every day clean up automatically)

**Comment by maximejobin** [comment]
I confirm it's working now.
