### ISSUE TITLE
Glotdict does not check for non typographic quotes

### ISSUE THREAD

**Issue by La-Geek** [Mte90/GlotDict#241]
Browser: Chrome 
Link: https://translate.wordpress.org/projects/wp-plugins/wc-frontend-manager/dev/de/formal/?filters%5Bterm%5D=%22&filters%5Buser_login%5D=&filters%5Bstatus%5D=either&filter=Filter&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc 

as an example, it is everywhere

Locale used: German de-DE

Default settings
![quotes](https://user-images.githubusercontent.com/1585416/61186757-46bbcb00-a669-11e9-8da5-1165cdae0dbb.png)

**Comment by Mte90** [comment]
There is a setting about non-typographic quotes, is that not working?

**Comment by La-Geek** [comment]
Hello Daniele, 
what setting do you mention? I have attached a screenshot, these are my settings.

But probably I have misunderstood the function? Does it validate the non-typographic quotes, when you *approve* a string? In my, in this, case, it does not warn me about wrong quotes.

I did not test, what happens, when you suggest a string (save) with non-typographic quotes.

**Comment by La-Geek** [comment]
Sorry, 
This was the wrong "settings" screenshot.

-  Show a warning for missing curly apostrophe in preview.
-  Show a warning for using non-typographic quotes in preview (except for HTML attributes quotes).
both are ticked/checked.

When I click on **_save_**, I see warnings, when I click on **_approve_**, no warnings appear.

**Comment by garrett-eclipse** [comment]
Hi @La-Geek that sounds correct.

Warning are flagged on saving a translation or during the Review process. When approving there's no warnings flagged as it's expected you've already checked it either through the Review process or manually and are therefore approving. 

If I've gotten the issue confused please feel free to re-open but from my understanding of what you're stating that's expected behaviour.

**Comment by La-Geek** [comment]
Yes, I'd already guessed. It is a pity. Would be a great feature :)

**Comment by garrett-eclipse** [comment]
I'm not sure we'd want to block an approve when the warnings can be triggered by running a Review on the waiting strings
