### ISSUE TITLE
Reject/Fuzzy side buttons not available on load for Waiting strings

### ISSUE THREAD

**Issue by garretthyder** [Mte90/GlotDict#243]
When you have waiting strings you have the reject/fuzzy options available on expand but on load they're not showing in the sidebar. After you reject a string though they do appear in the side.
Screencast of issue:
![69bd43c873461221f35bd8808cb1b267](https://user-images.githubusercontent.com/8726005/61998884-40671f00-b06b-11e9-9b80-b1484a79024b.gif)

**Comment by Mte90** [comment]
I tested now and this problem is not happening anymore.

**Comment by garretthyder** [comment]
Thanks @Mte90
