### ISSUE TITLE
Review button now hidden in 'Sort' dropout

### ISSUE THREAD

**Issue by garretthyder** [Mte90/GlotDict#250]
Browser: Chrome
Link: https://translate.wordpress.org/projects/wp-plugins/dokan-lite/dev/en-ca/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting
Locale used: en-ca

Hey @Mte90 seeing the Review button has moved. Was there an update to the extension or maybe translate.wp.org?
<img width="777" alt="Screen Shot 2020-05-08 at 8 52 42 AM" src="https://user-images.githubusercontent.com/8726005/81423610-8a585780-9109-11ea-902a-0c97c49526dc.png">

Thanks

**Comment by Mte90** [comment]
It is more simple to fix the selector inside the extension itself.
