### ISSUE TITLE
When using "formal" the GlotDict is not working properly, only missing points and ? are reported

### ISSUE THREAD

**Issue by psmits1567** [Mte90/GlotDict#252]
Browser: FireFox and Chrome
Link: https://translate.wordpress.org/projects/wp/dev/nl/formal/?filters%5Bstatus%5D=untranslated
Locale used:nl_NL

When you have this selected for locale nl_NL the wrong verbs are no longer reported. E.g. it does not use the Dutch Glossary to report missing verbs. It seems to me that this path is not within the standard translation locations

Two other users have reported the same issue, but they have this problem when translating plugins/themes.
They made sure the locale is set within Firefox and their profile on translate.wordpress.org

**Comment by Mte90** [comment]
GlotDict doesn't anymore inject the glossaries, the locale settings is used to inject links to the right locales inside the stats page as today.

There is a bug with non-pte users that don't let glotdict to work fine but I fixed it and I will release a new version now.

**Comment by psmits1567** [comment]
Problem has been tested with Firefox, and is fixed
Thanks for your quick support!
