### ISSUE TITLE
Sometimes clicks on Approve, Reject, Fuzzy GD buttons don't do anything

### ISSUE THREAD

**Issue by webaxones** [Mte90/GlotDict#257]
Browser: Firefox & Chrome
Link: Everywhere
Locale used: fr (french)

Hello,

First of all, a big thank you for this extremely useful tool.
I found a bug that is not very easy to reproduce on the clicks of the Reject, Approve and Fuzzy buttons.
Sometimes the action just doesn't happen.
I made a small video, where I reject an already validated translation (it can happen): it is correctly rejected. I then click on Approve and nothing happens.
It can happen with any of the buttons/actions.
https://www.dropbox.com/s/ry98bv6x0ofnfxd/glotdict.mp4?dl=0

Thanks
Loïc

**Comment by Mte90** [comment]
I am releasing a new version now.

**Comment by Mte90** [comment]
I added you also in the list of contributors in the readme.
