### ISSUE TITLE
Scroll to doesn't find it's target

### ISSUE THREAD

**Issue by Presskopp** [Mte90/GlotDict#268]
Browser: Chrome
Link: https://translate.wordpress.org/stats/
Locale used: de_DE

Button says "Scroll to **de_DE**" but scrolls to **de_DE_formal**

**Comment by Mte90** [comment]
I thought that was fixed. Well we need to check that again.

**Comment by Presskopp** [comment]
You fixed #256, but looks like this is a different issue
