### ISSUE TITLE
Recognition of wrong strings not always perfect.

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#271]
Browser: Opera
Link: N/A
Locale used: nl_NL/nl_BE

So, I noticed that when I'm translating or checking a sentence with e.g. twice "YOU" in it, and I translate it once correctly and a second time wrongly, GlotDict doesn't always block me.

Secondly, in nl_NL we translate "website" to "site"... but if you translate it as "website"... since most likely GlotDict sees "site" it doesn't block the user.

**Comment by Mte90** [comment]
There are some string we can use for some tests?

**Comment by NekoJonez** [comment]
I'll post here as soon as I encounter some. I thought I had some saved by my bookmarks are gone >.>

Sorry about this. I'll keep ya posted.

**Comment by NekoJonez** [comment]
@Mte90 For the "Website" issue... 

https://translate.wordpress.org/projects/wp-plugins/wp-optimize/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9957331&filters%5Btranslation_id%5D=73442667

Here is one.

**Comment by NekoJonez** [comment]
Can be closed, since it's better described and logged in #352
