### ISSUE TITLE
Glossary and words with a "-" / Exception list?

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#275]
So, in nl_NL & nl_BE we have in our glossary: "add" translate to "toevoegen". 

Now, there are words like "add-on" which we translate as "add-on". Yet, GlotDict blocks me because I didn't translate "add" as "toevoegen". 

To be honest, I don't know a solution for this "edge case". Since, if you build in something that it shouldn't block you if the word is like that... I think it might break other things. 

Maybe you could add a personal exception list? Like when "add-on" is shown, GlotDict doesn't need to block suggestions when you didn't translate "add-on" as "toevoegen-on" or something? 

Just a thought. 

Edit: another example:

"content" we translate to "inhoud"

but "wp-content" should stay "wp-content" and not become "wp-inhoud" or something.

**Comment by Mte90** [comment]
I think that there is an issue in our code that don't support the `-` symbol

**Comment by Mte90** [comment]
Can I get a link with the issue?

**Comment by NekoJonez** [comment]
It seems that currently, this fixed itself either through updates or through me adding all the other words in the glossary. 
I'll keep an eye on it and (re)open this if it pops up again.

**Comment by NekoJonez** [comment]
I found an example here: https://translate.wordpress.org/projects/wp-plugins/simple-history/dev/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=17348678&filters%5Btranslation_id%5D=115380012

"add-on" is one word, yet either GlotDict or GlotPress is seeing it as two... GlotDict also stops you if you don't use the right word.

**Comment by pedro-mendonca** [comment]
Hi @NekoJonez 
From what I see in https://translate.wordpress.org/locale/nl/default/glossary/, there is no 'add-on' glossary entry, but only 'add', so the match for 'add' seems correct.
Have you tried to add 'add-on' to the glossary?

![imagem](https://github.com/Mte90/GlotDict/assets/7371591/0a2120aa-abf9-4bb9-b62d-8942175e331e)

**Comment by NekoJonez** [comment]
@pedro-mendonca I am not a GTE for nl_NL, only nl_BE. It fixes this issue completely... But we shouldnt count on GTE's adding things to glossaries since others use this tool too and otherwise you need to make sure you got all exceptions.

**Comment by NekoJonez** [comment]
@pedro-mendonca I am not a GTE for nl_NL, only nl_BE. It fixes this issue completely... But we shouldnt count on GTE's adding things to glossaries since others use this tool too and otherwise you need to make sure you got all exceptions.

**Comment by NekoJonez** [comment]
Its a very double edged sword here... Since with if there was a typo here and the original says "add on" like in a sentece "add on top of that..."

**Comment by Mte90** [comment]
Looking at the code there isn't anything that GlotDict can do for this.

https://github.com/Mte90/GlotDict/blob/3fc09a6808e21411aa47404672ffd25fae3928cc/js/glotdict-validation.js#L57

We read form the HTML page the various glossary words and we check if they are used in the translation, so GlotPress needs to provide the right terms.
You should report that in GlotPress.
