### ISSUE TITLE
Glossary item comment is unnecessarily annotated

### ISSUE THREAD

**Issue by naokomc** [Mte90/GlotDict#28]
When a glossary item comment contains any word that is a part of the glossary, the word within the comment gets annotated & breaks the layout. See:

<img width="769" alt="translations___japanese___development___glotpress_ _wordpress" src="https://cloud.githubusercontent.com/assets/34067/15064985/89c5d02c-1395-11e6-920d-584f8e1bf218.png">

In the example above, the term "editor" has this comment: "	Editing tool (e.g. visual editor, theme editor, plugin editor)." Since "theme" and "plugin" are also glossary terms, they are causing this issue.

- [Link to the string](https://translate.wordpress.org/projects/apps/android/dev/ja/default?filters[status]=either&filters[original_id]=2772920&sort[by]=translation_date_added&sort[how]=asc) (Click the "details" link to see this)
- Glossary selected: [Japanese](https://translate.wordpress.org/projects/wp/dev/ja/default/glossary)

**Comment by Mte90** [comment]
Bug confirmed i work on it, thank you for the report.

**Comment by Mte90** [comment]
the next 1.0.8 release will fix this problem :-)
