### ISSUE TITLE
Scroll to misses language

### ISSUE THREAD

**Issue by Presskopp** [Mte90/GlotDict#284]
Browser: Chrome 92.0.4515.131 (64-Bit)
Link: https://translate.wordpress.org/stats/
Locale used: de_DE

![image](https://user-images.githubusercontent.com/18373563/129705383-e495129e-bf78-4b09-92df-e392931f43c4.png)

**Comment by webaxones** [comment]
Hi,
I just changed my locale to de_DE, then update GlotDict in 1.7.0 and I still have a Scroll to de_DE button that goes to the correct row.
Have you cleared your browser cache?
And do you have a message in the console (code inspector)?

**Comment by Mte90** [comment]
Maybe he didn't configured that value?

**Comment by Mte90** [comment]
We should print "You didn't set any locale yet." for those cases instead of the button.

**Comment by Presskopp** [comment]
oh my, yes I deleted browser cache and had to choose language again. But at least this gave us the input to change the button in that case :-)

**Comment by vlad-timotei** [comment]
Although the above PR fixes the issue, I don't think it's very user friendly. It tells the user they didn't set any locale yet, but they don't know how to do that. 

Ideally, the locale picker should be displayed instead.

**Comment by Mte90** [comment]
It should appear on the top with the GlotDict button, right?
Maybe we can mention it in the pr?

**Comment by webaxones** [comment]
What we maybe need is a way to communicate to the user, like a banner, as @Mte90 imagined to ask questions to users (other ticket). This same banner could be used to display this type of information.
