### ISSUE TITLE
Inconsistency location of #gd-language-picker

### ISSUE THREAD

**Issue by vlad-timotei** [Mte90/GlotDict#287]
#gd-language-picker is added
- to the bottom for PTE/GTE, because
`gd_filter_bar = jQuery('.filter-toolbar form div:first');`
selects the second .filter-toolbar available for PTE/GTE
- to the top for non PTE/GTE, because the first .filter-toolbar is selected, the second one doesn't exist.

Is this on purpose? 
Where do we want this to actually be displayed? It should be consistent.

- non GTE/PTE:
![image](https://user-images.githubusercontent.com/65488419/129915298-edd65bf6-91c8-48c8-8258-247b2f86aa5f.png)

- GTE/PTE
![image](https://user-images.githubusercontent.com/65488419/129915322-132e9274-a16f-4b9c-9ce7-94c052da8658.png)

**Comment by Mte90** [comment]
It was both because people doesn't notice and in this way it is like do it!
But if we add banners is not a problem to change it.

**Comment by vlad-timotei** [comment]
With #320 in place we can stick to a single top location for the language picker. 🎉 *(PR to be submitted soon)*
