### ISSUE TITLE
Source string does not allow multiple translations for string

### ISSUE THREAD

**Issue by webaware** [Mte90/GlotDict#30]
The JSON files are currently keyed by source string, directly mapped to a single translation. This is too restrictive and not how GlotPress accommodates dictionaries.

For one thing, strings can be translated by part of speech -- noun, verb, adjective, etc. -- and can have different translations in each of those modes. As an example, in Australian English the word `license` is `license` (same) when a verb but `licence` (different) when a noun. You can see these two translations in the [GlotPress dictionary](https://translate.wordpress.org/projects/wp/dev/en-au/default/glossary) but the [GlotDict dictionary has lost the noun translation](https://github.com/Mte90/GlotDict/blob/master/dictionaries/en_AU.json#L382-L386) (the useful one).

For another, context can change the required translation and that can be differentiated by the comments for a string. As an example, for Australian English we've added `unorganized` with two translations (`disorganised` and `unorganised`) separated by comments. The [GotDict dictionary has lost one](https://github.com/Mte90/GlotDict/blob/master/dictionaries/en_AU.json#L787-L791).

I propose that the mapping be to an array of translations, like this:

```
"license": [
    {
        "comment": "",
        "pos": "noun",
        "translation": "licence"
    },
    {
        "comment": "",
        "pos": "verb",
        "translation": "license"
    },
]
```

That obviously changes things significantly, so I imagine some discussion may be required.

**Comment by Mte90** [comment]
With your proposal i can modify glotdictjson (https://github.com/Mte90/GlotDictJSON) to check for multiple terms and add the correct change for glotdict without problems.

The problem it is, I cannot show two tooltips for it, so I need to use a single tooltip with this informations like:
pos: noun, verb
translation: licence,license
In this way i can resolve easily, what do you think?

**Comment by webaware** [comment]
I don't think that's sufficient. What happens for comment-differentiated strings?

See the w.org translator handbook for an [example of how GlotPress handles multiple translations](https://make.wordpress.org/polyglots/handbook/translating/glossary-style-guide/#getting-started). Perhaps you can have the tooltip show similarly?

**Comment by Mte90** [comment]
I didn't know that do you know a page where it is showed that tooltip?
In this way i can do some test to replicate it :-)

**Comment by webaware** [comment]
From the WordPress 4.5.x Japanese set: [Editor toolbar](https://translate.wordpress.org/projects/wp/dev/ja/default?filters[status]=either&filters[original_id]=203806&filters[translation_id]=9658637)

**Comment by Mte90** [comment]
Done, now support that system and all the dictionaries are updated :-)
The next  1.0.8 will have this fix :-)

**Comment by webaware** [comment]
Beaut, thanks!
