### ISSUE TITLE
Avoid repetitions of HTML tags detection and therefore improve speed by replacing JS with CSS

### ISSUE THREAD

**Issue by webaxones** [Mte90/GlotDict#302]
As @vlad-timotei pointed out, the detection of the presence of HTML tags to know if we are on a translation page or if the current user is an editor could be replaced by reading the global variable $gp .
With this in mind, we could for example add 2 CSS classes to the body at the very beginning of glotdict.js like this:
```javascript
'use strict';

const glotdict_version = '1.0.1';

( 'undefined' !== typeof $gp ) && document.body.classList.add( 'gd-on-translations' );
( 'undefined' !== typeof $gp_editor_options ) && '1' === $gp_editor_options.can_approve && document.body.classList.add( 'gd-user-is-editor' );
```

This would allow us, among other things, to replace the 3 lines ending the glotdict.js file:
```javascript
if ( jQuery( '.gp-content #upper-filters-toolbar' ).length > 0 ) {
	jQuery( '.gp-content' ).css( 'max-width', '85%' );
}
```

By this in the style.css file:
```css
.gd-on-translations .gp-content{
	max-width:85%;
}
```

**Comment by vlad-timotei** [comment]
For the record, I just found a case where $gp.editor is defined, but no actual editor is present on the page! 😞 
https://translate.wordpress.org/projects/wp/dev/

And all similar URL 
/projects/`${project_name}`/
/projects/`${project_name}`/`${subproject_name}`/
/projects/`${project_name}`/`${subproject_name}`/`${project_type}`/

All these statistical projects for a certain project have `$gp`  erroneously defined, but luckily, they don't have `$gp_editor_options`  defined, so we could rely on that.

**Comment by webaxones** [comment]
For me it is not a problem that these pages pass in 95% as well, but since there is a change, we will wait @Mte90 's opinion.

**Comment by webaxones** [comment]
So if I summarize:
1. If we merge this code, translations tables will be at 85% but also pages like `https://translate.wordpress.org/projects/wp/dev/` (I'm not sure it's fine on 2560px, if there wasn't any hover on the table I might not be able to find which locale the values correspond to. But majority doesn't have big screens).
2. We change the code for this:
```javascript
( 'undefined' !== typeof $gp_editor_options ) && '0' === $gp_editor_options.can_approve && document.body.classList.add( 'gd-user-is-translator' );
( 'undefined' !== typeof $gp_editor_options ) && '1' === $gp_editor_options.can_approve && document.body.classList.add( 'gd-user-is-editor' );
( 'undefined' !== typeof $gp_editor_options ) && document.body.classList.add( 'gd-on-translations' );
```
Like this, we will therefore have CSS class to target editors or translators (for next soon steps) and one to target table translations for the max-width.

**Comment by vlad-timotei** [comment]
Note that `$gp_editor_options.can_approve` is `"1"` for editors, but is not `"0"` for others. Instead, it is `""`.

**Comment by webaxones** [comment]
Yep, so:
```javascript
( 'undefined' !== typeof $gp_editor_options ) && '' === $gp_editor_options.can_approve && document.body.classList.add( 'gd-user-is-translator', 'gd-on-translations' );
( 'undefined' !== typeof $gp_editor_options ) && '1' === $gp_editor_options.can_approve && document.body.classList.add( 'gd-user-is-editor', 'gd-on-translations' );
```
