### ISSUE TITLE
Layover should be removed

### ISSUE THREAD

**Issue by webaxones** [Mte90/GlotDict#308]
I managed to get the layover to work by moving its addition to the glotdict-locales.js file.
But even on this test below (WP core with a setting of 10,000 rows per page), we can clearly see that the waiting time is 80% dependent on the site, and not on the extension.

So I think we should remove this feature.

![10000strings](https://user-images.githubusercontent.com/17084006/131550950-ccd4423a-0493-4304-b55a-22285de2dfe1.gif)

**Comment by vlad-timotei** [comment]
So, to understand this better. 
@Mte90 what was the original purpose of this layover?

Do we have any benefits out of it?
If yes, then maybe (I don't know if it actually works) run a script `"run_at": "document_start"` with a layover? That way, the entire page loading process would have a layover?

**Comment by webaxones** [comment]
I think we wouldn't have benefits cause a loader add repaints of the DOM, so add more time to load.
Which would prolong processing for all users, not just those with a lot of rows per page.

**Comment by vlad-timotei** [comment]
Moreover, having a visual loader, IMHO, makes the user more aware of the waiting time, some might even thing that it's GD's fault for this waiting time. 

What I wonder is if it affects GD in some way if user starts interacting with the site before GD ends to load stuff. If not, then maybe we can remove the loader.

**Comment by Mte90** [comment]
The layover was implemented for this reason https://github.com/Mte90/GlotDict/issues/110 but we are talking of 2017.
Let's see if it is still needed, basically it is a way to avoid people to use the page until is fully loaded or there will be support requests.

**Comment by webaxones** [comment]
Well, I tried to reproduce #110 but for me this is a user behavior error and not a problem with the extension. Then I have in mind an optimization that I would like to do about the number of loops on the table (I would like to reduce it to 1) and I think that the problem should not happen again since the buttons would be added last.
