### ISSUE TITLE
Provide the glossary term if the word is uppercase or lowercase

### ISSUE THREAD

**Issue by fxbenard** [Mte90/GlotDict#31]
It seems that if the word in the glossary is uppercase, it don’t show for the lowercase.

E.g. in French permissions is in the glossary, but we don't have any suggestion for Permissions

Any chance to change this behavior? thanks

**Comment by Mte90** [comment]
very strange, the code is case insensitive...
do you have a page so i can test it?

**Comment by fxbenard** [comment]
OK my bad I tested it again, it works for uppercase/lowercase. 

It was a problem of singular/plural in the glossary and in the source. That is not working.

You can close the issue, sorry.

**Comment by Mte90** [comment]
No problem :-)
