### ISSUE TITLE
This line can be deleted unless someone knows what it is for

### ISSUE THREAD

**Issue by webaxones** [Mte90/GlotDict#313]
I think this can be deleted because with or without the behavior is the same (Chrome & Firefox)
There must have been a reason at the time, but it's probably gone.
https://github.com/Mte90/GlotDict/blob/d8cf142a2ea3d424c3243f5bf6e1c9820f1f0395/js/glotdict.js#L20

**Comment by Mte90** [comment]
This was to fix some alignment issues when the select menu for the language was added on first usage.
If it is not need anymore you can remove it.

**Comment by vlad-timotei** [comment]
I can't see any difference with or without that `clear: both` either. 

## Chrome:
![gd_issue_313_chrome](https://user-images.githubusercontent.com/65488419/131899800-789ab0c7-d689-4f78-9573-effa9f0b1451.gif)

## Firefox:
![gd_issue_313_firefox](https://user-images.githubusercontent.com/65488419/131899802-b3dd8c08-c69c-48ca-ab99-b0827afaf2d9.gif)

This means we need to even better document our PR's with before and after screenshots for future us/devs that will wonder why something was done. 😆 

Seems ok to be removed.

**Comment by Mte90** [comment]
Ok remove it, I think I added that when it's was just me on the project years ago 😂

**Comment by webaxones** [comment]
Maybe it was just something needed with previous versions of GlotPress!
I remove it :)

**Comment by vlad-timotei** [comment]
This was fixed in #314
