### ISSUE TITLE
Improve settings descriptions

### ISSUE THREAD

**Issue by vlad-timotei** [Mte90/GlotDict#315]
This **proposal** aims at making settings descriptions more easy to understand.
General guidelines I tried to follow here:
- Use **affirmative verbs**: show, hide, save etc. Negations will result in double negations when the setting is disabled. 
- Use the same sentence construction when possible.
- Keep it short
- Group settings by their usage/type

Proposed settings texts (simple enough for any user to understand the settings)
![image](https://user-images.githubusercontent.com/65488419/132446682-86be40e1-a402-4b53-ae4f-2103dc2a9021.png)

| Current setting text | Category | Proposed text | What code does |
| -- | -- | -- | -- | 
| Don’t show a warning when the translation is missing a glossary term. | **Hide warnings for:** | missing glossary terms | Checks if translation contains glossary terms. ([ref](https://github.com/Mte90/GlotDict/blob/master/js/glotdict-validation.js#L36)) | 
| Don’t show a warning when the translation doesn't contain an initial uppercase letter when the original string starts with one. | Hide warnings for | missing start capitalization | When the original is capitalized, checks if the translation also is capitalized. ([ref](https://github.com/Mte90/GlotDict/blob/bc2cf68df6d8c97560258d2f6f17cca03f8b39fb/js/glotdict-validation.js#L120)) |
| Hide warning for initial space in translation. | Hide warnings for | missing start space | Checks if translation is missing a starting space or non-breaking space. ([ref](https://github.com/Mte90/GlotDict/blob/bc2cf68df6d8c97560258d2f6f17cca03f8b39fb/js/glotdict-validation.js#L126)) |
| Hide warning for trailing space in translation. | Hide warnings for | missing end space | Checks if translation is missing an ending space or non-breaking space. ([ref](https://github.com/Mte90/GlotDict/blob/bc2cf68df6d8c97560258d2f6f17cca03f8b39fb/js/glotdict-validation.js#L132)) |
| Don’t validate strings ending with “...“, “.”, “:” | Hide warnings for | missing end hellip `…` | When original ends with `...` (three dots), translation can’t end in `...` (three dots). Instead, translation must end in `&hellip;`, `.` (dot) or `…` (hellip) ([ref](https://github.com/Mte90/GlotDict/blob/bc2cf68df6d8c97560258d2f6f17cca03f8b39fb/js/glotdict-validation.js#L105)) |
| Don’t validate strings ending with ;.!:、。؟？！| Hide warnings for | missing end symbols  `; . ! : 、。؟ ？！` | When original doesn’t end with `...` (three dots) and original ends with any symbol from the list `; . ! : 、。؟ ？！`, checks if translation ends in one of those symbols as well. ([ref](https://github.com/Mte90/GlotDict/blob/bc2cf68df6d8c97560258d2f6f17cca03f8b39fb/js/glotdict-validation.js#L112)) |
|  |  |  |  |
| Show a warning for missing curly apostrophe in preview. | **Show warnings for:** | straight single quote ` ' ` | If setting enabled, checks and warns for straight single quote ` ' ` in translation ([ref](https://github.com/Mte90/GlotDict/blob/f5e3390057a6015e89f50dfa6db6e73dbd0c89fb/js/glotdict-validation.js#L138)). If setting disabled, highlights curly apostrophe `’` in preview ([ref](https://github.com/Mte90/GlotDict/blob/60ebe156604070369d7281ecca3261578f2c93aa/js/glotdict-functions.js#L258)) |
| Show a warning for using non-typographic quotes in preview (except for HTML attributes quotes). | Show warnings for | straight double quote `"` | Checks if translation has straight quotes `" "`, excluding HTML tags. ([ref](https://github.com/Mte90/GlotDict/blob/f5e3390057a6015e89f50dfa6db6e73dbd0c89fb/js/glotdict-validation.js#L144)) | 
|  |  |  |  |
| Don’t visualize non-breaking-spaces in preview. | **Others** | Hide highlights for non-breaking spaces. | Highlights non-breaking-spaces in preview. ([ref](https://github.com/Mte90/GlotDict/blob/69cf2f6242ff99a935eb88f7c7d0d6939029c29a/js/glotdict-functions.js#L242)) |
| Auto-submit the "Copy From Original" Bulk Action (Warning: When enabled will submit all originals). | Others - Use with caution! | Auto-save after "Copy from Original" bulk action. | Auto-submits translations on Copy from Original bulk action: will fire Save button if no warnings. ([ref](https://github.com/Mte90/GlotDict/blob/f5e3390057a6015e89f50dfa6db6e73dbd0c89fb/js/glotdict-bulk.js#L15)) |  
| Don’t validate strings during "Copy From Original" Bulk Action to bypass validation. (Warning: When enabled will submit originals with Glossary terms or other warnings.) | Others - Use with caution! | Ignore auto-save warnings after "Copy from Original". | Auto-submits translations on Copy from Original bulk action: will fire Save button regardless of the warnings! ([ref](https://github.com/Mte90/GlotDict/blob/f5e3390057a6015e89f50dfa6db6e73dbd0c89fb/js/glotdict-bulk.js#L21)) |

Note: 
- To validate means either the proces of validation or its immediate result (save or warning), so its usage can be confusing.
For clarity: `Don’t validate strings` -> `Don't perform the validation process` -> `Don't show warnings` -> `Hide warnings`
- This doesn't change any setting logic, so they can't be all grouped under the same category of Show/Hide without code modifications. If we want, this can be a next step, keeping in mind not to break current user's saved settings.

**Comment by webaxones** [comment]
Jenny will be able to use this table as it is in the documentation! Great!
