### ISSUE TITLE
Part of the phrase underlined instead of only a glossary word

### ISSUE THREAD

**Issue by sgelob** [Mte90/GlotDict#32]
Discovered this issue then the entire phrase (or it’s part) is underlined (dotted), instead of only the interested word from the glossary.

For example look at the word **sure** here: https://translate.wordpress.org/projects/wp-plugins/wp-photo-album-plus/stable/it/default?filters%5Bterm%5D=Nuovo+Album&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

<img width="345" alt="screen shot 2016-05-13 at 12 02 57" src="https://cloud.githubusercontent.com/assets/6544108/15244802/41b6fdc4-1903-11e6-9e3e-2e20cfb0e41a.png">

Thank you in advance for the fix ;)

**Comment by Mte90** [comment]
In this case:
`"are you sure you want": {
        "comment": "", 
        "pos": "", 
        "translation": "desideri"
    }, 
`
It is defined in the Italian glossary that terms so the only way is to change the glossary itself.
