### ISSUE TITLE
Add extra separator to links in H2

### ISSUE THREAD

**Issue by vlad-timotei** [Mte90/GlotDict#328]
Case 1: project doesn't have Glossary, but User is GTE/PTE and sees "Create a Glossary" link
![image](https://user-images.githubusercontent.com/65488419/133660551-4f73052b-6457-4d43-8bd2-fcaf7a0a8397.png)

Case 2: project has a Glossary and user can have any role.
![image](https://user-images.githubusercontent.com/65488419/133660603-8f329549-089c-468e-b7aa-b9d138f39303.png)

Case 3: project doesn't have a Glossary, user is not GTE/PTE => all good.
![image](https://user-images.githubusercontent.com/65488419/133660817-693a122e-3b31-49aa-bb7e-1f5fd80787f2.png)

We need to find a way to append/prepend these extra links with a | **where applicable**, because there is case 3.

Reported by: @NekoJonez

**Comment by vlad-timotei** [comment]
Fixed in # 337

**Comment by psmits1567** [comment]
In my opinion this can be closed as we now have bullets between the text. Also the import page has changed, as there is no header present anymore
