### ISSUE TITLE
document.execCommand is deprecated

### ISSUE THREAD

**Issue by webaxones** [Mte90/GlotDict#335]
document.execCommand used in gd_copy_to_clipboard function is deprecated and should be replaced with Clipboard API:
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by DillonKyleDev** [comment]
Hey there! 
I think I'd like to give this a go if that's alright.

**Comment by webaxones** [comment]
For sure!
The more the merrier :)
What we need to check is if this does not require asking users for additional permissions, because we could not ask more than 500 users for additional permission just for 1 action. But I don't know yet. I am always wary of web extensions: anything simple is complicated in this world :D
Anyway, welcome!
