### ISSUE TITLE
Improve code of settings.js by replacing last jQuery occurrences

### ISSUE THREAD

**Issue by webaxones** [Mte90/GlotDict#339]
Replace the jQuery code present in the settings.js file with native JS while respecting the ESLint rules as well as the gd_ prefix for any global, variable or function.

**Comment by DillonKyleDev** [comment]
I'm not super familiar with JQuery but I'd like to try my hand!

**Comment by Adnan-Sait** [comment]
Is this change still required?
If so, I would love to take this up.

**Comment by Mte90** [comment]
The PR is on https://github.com/Mte90/GlotDict/pull/340 but wasn't finished after our review an year ago

**Comment by Adnan-Sait** [comment]
Yeah, I noticed that the requested changes were not made.
Would it be ok for me to start working on this issue from scratch and raise another Pull Request?

**Comment by Mte90** [comment]
yes it is perfectly fine

**Comment by Adnan-Sait** [comment]
I have made the changes. One major change is in the checkbox click event listener.
https://github.com/Mte90/GlotDict/pull/395

In JQuery, we register the listeners globally, and JQuery applies the listeners to the individual checkboxes.
With Vanilla JS, I have configured the event listeners after the checkboxes have been rendered on the DOM.
