### ISSUE TITLE
Only fixing a word once is enough to stop the warnings

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#353]
In nl_BE, we don't shorten website to site. But, if you correct it only ONCE and leave the others as "site"... Glotdict doesn't stop you. 
EVEN when the warnings before the correction showed up that you were missing the term several times.

**Comment by vlad-timotei** [comment]
See #352. I think it has the same cause.

**Comment by vlad-timotei** [comment]
So, currently GD only checks if the glossary definition is included in the translation (at least once).
We could actually count the number of times it should be used.
