### ISSUE TITLE
Spaces in glossary are ignored.

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#355]
https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3440816&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=desc&historypage

-> in nl_NL, in the glossary there is a line for "admin bar" to translate it to "toolbar". Yet, nor GlotPress nor GlotDict warns you when you mistranslate it. 

This is just one example. I'm under the impression that as soon as there is a space in a word in the glossary, it gets ignored.

**Comment by vlad-timotei** [comment]
Thank you for the issue. 
As explained [here](https://meta.trac.wordpress.org/ticket/5956) the issue is already being tracked upstream in the GlotPress repo - since GlotPress is the one marking the terms as being part of a glossary.
