### ISSUE TITLE
string reloads and replacements are pasted at the end of the string - unable to edit.

### ISSUE THREAD

**Issue by Presskopp** [Mte90/GlotDict#357]
Browser: Chrome 96.0.4664.110
Link: https://translate.wordpress.org/projects/wp-plugins/relevanssi/dev/de/default/?filters%5Bterm%5D=Du+hast+keinen+Index
Locale used: de_DE/default
see video

https://user-images.githubusercontent.com/18373563/146532417-3431952a-61c2-4b7c-a989-a2051d34c60d.mp4

o

**Comment by vlad-timotei** [comment]
Hi, @Presskopp 
Thank you for the issue!

After some debugging and the additional info you gave me, I came to the conclusion that this is a WPGPT bug.
GlotDict doesn't introduce `Alt + numbers` keyboard shortcut. WPGPT overrides the native `Alt + numbers` shortcut for special characters to insert consistency suggestions. You can disable all custom shortcuts in the WPGPT settings.

Thanks again for reporting this behavious.
