### ISSUE TITLE
Broken back to top link

### ISSUE THREAD

**Issue by webaxones** [Mte90/GlotDict#360]
Replace #wporg-header with #global-header in gd_scroll_to_top function.
(Broken from wp org new styles)

**Comment by vlad-timotei** [comment]
Actually, `#global-header` will always be in view because the global header is sticky now.
So a better choice would be `#masthead`

**Comment by webaxones** [comment]
So true! :D

**Comment by NekoJonez** [comment]
We are talking about this weirdness?
![image](https://user-images.githubusercontent.com/4569581/151783383-10ce7509-ab12-4cb6-a30a-f176d89ead17.png)

**Comment by Mte90** [comment]
Yes I released the new version that include the fix. We was waiting for the changes in Ui to be complete.

**Comment by NekoJonez** [comment]
I saw one minor thing in the settings panel... I just commented on the ticket there. #361, I'm trying to look if I find where that part of the code is located to fix it ;)
