### ISSUE TITLE
Refine styles and functionalities after translate.org implements new design

### ISSUE THREAD

**Issue by vlad-timotei** [Mte90/GlotDict#361]
Issue to keep track of all the broken styles and functionalities we need to refactor, after the new w.org design is implemented.
Most of these issues need upstream fixes before they can implement a permanent fx.
Follow [this ticket](https://meta.trac.wordpress.org/ticket/6037) and other related ones.

- [x] 1. Switcher - fixed in https://github.com/Mte90/GlotDict/pull/364

![image](https://user-images.githubusercontent.com/65488419/150766781-2ce39a2f-91c1-4334-96a7-667519da75bb.png)

- [x] 2. Settings & What's new - fixed in https://github.com/Mte90/GlotDict/pull/364

![image](https://user-images.githubusercontent.com/65488419/150766867-5d7aa67c-477b-46ae-88ee-3b56c58af629.png)

- [x] 3. Has glossary words bar (checkbox position has been reported upstream) (Issue only for GTE/PTE) (fixed upstream)

![image](https://user-images.githubusercontent.com/65488419/150766991-aaee8fe1-d6b4-42bf-b304-63a1d8bf159f.png)

- [x] 4. Back to top link ([tracked here](https://github.com/Mte90/GlotDict/issues/360))

**Comment by NekoJonez** [comment]
Well, you could say this is an issue as well... Somewhat.
![image](https://user-images.githubusercontent.com/4569581/151782949-3e18f9eb-caab-41d1-a667-5585985e8cd1.png)


I think an enter between the shortcut table and the "*Please use features marked like this with caution!" would be a nice idea?
Since, now it looks like that warning message is talking about the shortcut table.

**Comment by Mte90** [comment]
I released a new version with various fixes for the UI after the translate.wordpress.org changes.

**Comment by NekoJonez** [comment]
I'm not too familiar with JS, but I think that the thing I'm talking about is at https://github.com/Mte90/GlotDict/blob/8916582590b8d2480377ba6ac5e248e16fbd8f37/js/glotdict-settings.js#L161

I'll look if it's still a bit strange in the new version report here.

**Comment by NekoJonez** [comment]
> I'm not too familiar with JS, but I think that the thing I'm talking about is at
> 
> https://github.com/Mte90/GlotDict/blob/8916582590b8d2480377ba6ac5e248e16fbd8f37/js/glotdict-settings.js#L161
> 
> I'll look if it's still a bit strange in the new version report here.

Now it's fixed :) Disregard my previous comments.

**Comment by NekoJonez** [comment]
Yeah, the 2.0.4 patch shows it now better :)

**Comment by vlad-timotei** [comment]
Version [2.0.4](https://github.com/Mte90/GlotDict/releases/tag/v2.0.4) fixed these issues above. 
Closing this for now.

Keeping an eye on translate.ow.org for future style modifications, as the styles upstream are not in their final form, some things still being broken upstream.
