### ISSUE TITLE
The transition of Chrome extensions to Manifest V3

### ISSUE THREAD

**Issue by vlad-timotei** [Mte90/GlotDict#365]
According to [this article](https://developer.chrome.com/blog/mv2-transition/) we have a year by now to migrate to manifest V3 if we want to be able to push updates after this date.

> January 2023: The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions.

Opening this ticket to track progress on this matter.

**Comment by vlad-timotei** [comment]
Seems like Mozilla has the same plans: https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/

**Comment by Mte90** [comment]
* https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/
So in firefox there will be compatibility, for is just https://github.com/Mte90/GlotDict/blob/master/js/background.js that require some changes and https://github.com/Mte90/GlotDict/pull/384/files already address it we need to do some tests.

**Comment by vlad-timotei** [comment]
Fixed by https://github.com/Mte90/GlotDict/pull/401
