### ISSUE TITLE
Pipes between links are missing in bar on the translation import page

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#367]
![image](https://user-images.githubusercontent.com/4569581/152687391-cd7266ac-d318-4949-92f2-cfc3b2d01b0d.png)

On the import page, the pipe characters are missing between the action links.

**Comment by vlad-timotei** [comment]
Thank you for the issue. 
The issue is tracked issue #328, reported by you :)

**Comment by NekoJonez** [comment]
I looked over that in my searching. Whoops
