### ISSUE TITLE
Word add-on not detected with french translation

### ISSUE THREAD

**Issue by xpatval** [Mte90/GlotDict#375]
Hello,

the word « add-on » is not detected by GlotDict although it is in the French glossary.

![image](https://user-images.githubusercontent.com/57391455/155119466-5108dd4c-1927-4efd-a085-46d8ba6d1df2.png)

**Comment by webaxones** [comment]
Sorry @xpatval I told you bullshits, it's not a GlotDict bug but a GlotPress one.
https://github.com/GlotPress/GlotPress-WP
:(
