### ISSUE TITLE
Italian Glossary – The word “found” is blank

### ISSUE THREAD

**Issue by sgelob** [Mte90/GlotDict#38]
The suggestion for the word **found** has a blank tooltip.

Chrome, Mac OSX

Example: https://translate.wordpress.org/projects/wp-plugins/broken-link-checker/stable/it/default?filters%5Bterm%5D=No+dismissed+links&filters%5Buser_login%5D=&filters%5Bstatus%5D=either&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

<img width="1044" alt="screen shot 2016-06-04 at 14 29 43" src="https://cloud.githubusercontent.com/assets/6544108/15799555/dda4a024-2a60-11e6-85cb-b5b275edbc87.png">

Thanks for the fix in advance ;)

**Comment by sgelob** [comment]
Same for the word “embed”… Some code conflict? :)

**Comment by Mte90** [comment]
As you can see they are empty https://github.com/Mte90/GlotDict/blob/master/dictionaries/it_IT.json#L52, on the gdoc they are not defined. In case i can ignore the terms empty and not show them.

**Comment by Mte90** [comment]
The 1.1.0 will use the glotpress version for italian that will not have that problem.
