### ISSUE TITLE
Error thrown in Opera

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#385]
![image](https://user-images.githubusercontent.com/4569581/162792562-1f8f5fdf-86b8-4093-b761-0429283815ad.png)

**Comment by Mte90** [comment]
Well the error is not valid as filenames doesn't start with `_`.
Are you sure that isn't an Opera bug?

**Comment by vlad-timotei** [comment]
Quoting @NekoJonez :

> Reinstalling GlotDict solved the issue. Might have been some cache.

Unless this reoccurs, I'd say we can close this.
Thanks for reporting.

**Comment by NekoJonez** [comment]
I think this can be closed @Mte90 and @vlad-timotei ... I have been using GlotDict & WPGP and never seen this error really return NOR affect the preformance of GlotDict.
