### ISSUE TITLE
Inappropriate warning messages

### ISSUE THREAD

**Issue by jennydupuy** [Mte90/GlotDict#392]
Browser: Chrome 103.0.5060.114
Link: https://translate.wordpress.org/projects/wp-plugins/webp-converter-for-media/stable/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=13007440&filters%5Btranslation_id%5D=95897360
Locale used: fr_FR

I want to correct a missing non-breaking space in the string, I make the change and then click on Save.
A large number of warning messages are displayed even though the glossary terms are not even present in the original string.

See the video:
![warning-not-appropriate](https://user-images.githubusercontent.com/75045144/178212384-504b032f-fa34-4737-857a-85a850ad5bfa.gif)

Context: I also have the chrome SPTE extension installed but the issue occurs even if I deactivate SPTE.

**Comment by vlad-timotei** [comment]
I've confirmed with @jennydupuy that she is a beta tester
Most probably it's related to this issue #391
