### ISSUE TITLE
Buttons in sidebar are glitchy - Wrong results shown

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#394]
I don't know if either a conflict with Transfill or WPGP tools is happening but... Or conflicts with some latest GlotPress updates...

But, I notice that when I click fuzzy, the color of the row doesn't change and sometimes when I reject a string... It shows as accepted!

I use Opera, the latest build at the time of writing.

**Comment by NekoJonez** [comment]
Note, while the colors don't change or change wrong... The right thing still happens.

**Comment by webaxones** [comment]
Hi @NekoJonez 
Can you do a little video capture for us to see what's going on please?
Thanks :)

**Comment by NekoJonez** [comment]
As I don't have the right computer to have screenrecording on right now... I made a screenshot... So, this happened after clicking reject. You can see at the 2nd line it's not coloring red.

![image](https://user-images.githubusercontent.com/4569581/183298307-ddf69111-83f8-452d-bfc4-6cf0ce28b67b.png)


Yet when I refresh: 

![image](https://user-images.githubusercontent.com/4569581/183298343-365367db-f0a8-463f-98bc-5234af81b723.png)

**Comment by NekoJonez** [comment]
After some further testing, it's WPTranslationFiller messing it up. When I disable that extension and refresh the page... GlotDict resumes normal operation. :) So, I'm going to close this ticket here since I think this isn't anything GlotDict related and open a ticket over at WPTransfill. If it's something GlotDict should do, I'll reopen this. I'm also going to ping Peter Smits on Slack about this.

**Comment by NekoJonez** [comment]
That issue also has a vid of the behaviour

**Comment by vlad-timotei** [comment]
Looks like the solution has been found in the issue above to make WPTF compatible with GlotDict. :)

**Comment by NekoJonez** [comment]
https://github.com/vibgyj/WPTranslationFiller/issues/231
@vlad-timotei , could this possibly be re-opened? Since, I think adding the CSS for the edge case in GlotDict would help us quite a lot. I also posted an improved CSS code for the new state.

**Comment by codinglater** [comment]
IMHO GlotDict shouldn't add code to be compatible with other extensions when those update. It is not sustainable. Its main purpose is to be compatible with GlotPress on w.org and as a main extension, other extensions should ensure compatibility with GlotDict. 

I don't see why the css can't be added in wptf if it is only needed when wptf is present. 😁

**Comment by vlad-timotei** [comment]
IMHO GlotDict shouldn't add code to be compatible with other extensions when those update. It is not sustainable. Its main purpose is to be compatible with GlotPress on w.org and as a main extension, other extensions should ensure compatibility with GlotDict. 

I don't see why the css can't be added in wptf if it is only needed when wptf is present. 😁

**Comment by NekoJonez** [comment]
> IMHO GlotDict shouldn't add code to be compatible with other extensions when those update. It is not sustainable. Its main purpose is to be compatible with GlotPress on w.org and as a main extension, other extensions should ensure compatibility with GlotDict.
> 
> I don't see why the css can't be added in wptf if it is only needed when wptf is present. 😁

Because the CSS in only WPTF doesn't fix the issue. And putting it in GlotDict & WPTF works. Oh well, then I'll just place it every time I guess :P

**Comment by vlad-timotei** [comment]
> Because the CSS in only WPTF doesn't fix the issue.

I will take a look and see how it can be implemented in WPTF.  I don't think GlotDict enforces any styles in ways that can't be overridden by WPTF
