### ISSUE TITLE
Copy from original not working?

### ISSUE THREAD

**Issue by lidialab** [Mte90/GlotDict#396]
Browser: Firefox 105.0.3 (64 bit) and Chrome 106.0.5249.103 (64 bit)
Chrome has only Glotdict extension installed.

Link: https://translate.wordpress.org/projects/wp-plugins/give/stable-readme/it/default/?filters%5Bterm%5D&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D&sort%5Bby%5D=priority&sort%5Bhow%5D=asc&sorts=Apply+Sorting&page=4

Locale used: it_IT

Steps:
I select some strings (untraslated), select "Copy From Original" from Bulk Actions, click on "Apply", but nothing happens and the checkboxes are unselected.

**Comment by vlad-timotei** [comment]
Thank you for the issue, Lidia.
Indeed GlotDict bulk action to copy from original is not working - because of a conflict generated by the `gp-translation-helpers` plugin that unchecks the rows if the rows are untranslated. We will look into this and find a solution asap. Thank you!

**Comment by lidialab** [comment]
Thanks for explanation Vlad!

**Comment by Mte90** [comment]
New release with the bugfix will be available in few hours.
