### ISSUE TITLE
Move the location of QuickLinks to acomodate new coming changes on w.org

### ISSUE THREAD

**Issue by vlad-timotei** [Mte90/GlotDict#402]
With the new upcoming changes on w.org, QuickLinks area is no longer available to use. 
<img width="1048" alt="Screenshot 2022-12-16 at 13 46 07" src="https://user-images.githubusercontent.com/65488419/208091499-e0912add-a2c8-44f5-afa4-dafdd5b5ce78.png">

Proposed new location:
<img width="771" alt="Screenshot 2022-12-16 at 14 00 09" src="https://user-images.githubusercontent.com/65488419/208093728-f51bd3f1-5508-4ba1-bdd1-5ec7929b7222.png">

Ideas?

**Comment by NekoJonez** [comment]
Thats a perfect spot. 
But like I said in slack, it should be possible to hook into those tabs to add one for e.g. the quicklinks.

**Comment by vlad-timotei** [comment]
Once the tabs will be in place we will see how we can leverage the use of them. 
IMHO QuickLinks shouldn't be in a tab, since we already have them in a menu - they should be upfront somewhere since they should be 1 click away.
