### ISSUE TITLE
Add a quick links button to the discussion page

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#404]
I think it would be an amazing little addition if there is a quick link icon to the discussion page of that string. 
So, the discussion can be full screen instead of the sidebar (which is upcoming)

**Comment by vlad-timotei** [comment]
There is already a PR for that at #399 that will land in a future version of GD.
However, please have a look at #402 regarding the new location of QuickLinks as the current location will no longer be available.
