### ISSUE TITLE
The accept button changes in the copy button.

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#406]
Possibly due to commit: https://meta.trac.wordpress.org/changeset/12677

The accept button in the sidebar changes into the copy button...

Example: 

![image](https://github.com/Mte90/GlotDict/assets/4569581/c64c7240-7365-4daa-a75a-b74c81397869)

**Comment by Mte90** [comment]
I am not able to replicate the issue in any link.
Can you share a link where is happening the issue?

Probably depends from https://github.com/Mte90/GlotDict/blob/342bf07ce3a5daada009008486e6429d2ea573a5/js/glotdict-column.js#L15 with `tr_preview.nextElementSibling.querySelectorAll( '.status-actions button.approve,.status-actions button.reject,.status-actions button.fuzzy' ).forEach( ( button ) => {`

**Comment by NekoJonez** [comment]
I'll try to give you a link soon. But have you tested it with also WPGP tools & TranslationFiller installed or only GlotDict? That way I can also help narrow down the issue.

**Comment by NekoJonez** [comment]
@Mte90 I had it happen here: https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/nl-be/default/?filters%5Bstatus%5D=current

Now, after some testing... This is getting interesting...
When I only run GlotDict, I don't get the issue of overly duplicate buttons... Yet, another button appears with "copy".

![image](https://github.com/Mte90/GlotDict/assets/4569581/413a83f0-eff2-419e-8b10-729325f08900)

Yet, as soon as I enable either WPGP Tools and/or WP Transfill... Duplication happens.

With WPGP tools active, WP Transfill inactive:
![image](https://github.com/Mte90/GlotDict/assets/4569581/4386c319-8b55-41d3-bfee-edc5ee67593d)

The screenshot is the exact same when I disable WPGP tools & activate WP Transfill... Yet, I notice that it happens less frequently then WPGP Tools.

So, somehow I think GlotDict is adding a button being a first bug and the other tools duplicating it being another bug?

**Comment by psmits1567** [comment]
WP Translation Filler does mothing with this mask. I have tested it with only GlotDict active, and it gives me the duplicate copy only with the first record of the list. I think if you fix GlotDict, then the other addons wil no longer have the problem

**Comment by psmits1567** [comment]
HI [Mte90](https://github.com/Mte90), as I can reproduce it, I have made a solution that fixes this issue
It happens as soon as you add a new translation, that contains several suggestions!
It creates the copy button with the same amount of the suggestions
This is the fix I made to prevent it
function gd_add_column_buttons( tr_preview)

Alter it to this, check for the class before adding the button
if ( ! tr_preview.classList.contains( 'untranslated' ) ) {
            if (!clone_button.classList.contains("copy-suggestion")){
			td_buttons.append( clone_button );
			}
		}

The copy buttons should not be added, as it has the wrong function
If you click on it, you will get an undefined error

**Comment by Mte90** [comment]
I am releasing a new version with the bugfix provided by @webaxones
