### ISSUE TITLE
If a translation contains this special character "..." a warning is shown, which is incorrect as the character is present

### ISSUE THREAD

**Issue by psmits1567** [Mte90/GlotDict#407]
GlotDict checks the end of the line for characters that do not belong there
In case the end of the line contains this special character "..." a warning is thrown that is not correct
So obviously GlotDict checks for the wrong value
Link to original
https://translate.wordpress.org/projects/wp-plugins/foogallery/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=11681282&filters%5Btranslation_id%5D=107172054

**Comment by psmits1567** [comment]
Checked it without GlotDict, then the error is not present. So it is definitively GlotDict that created the error

**Comment by psmits1567** [comment]
Currently it indicates &hellip is missing, which is incorrect

**Comment by Mte90** [comment]
So I tried the latest glotdcit version, configured IT locale and enabled the missing hellip in the settings on https://translate.wordpress.org/projects/wp-plugins/foogallery/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=11681282&filters%5Btranslation_id%5D=107172054

I don't see any alert

**Comment by psmits1567** [comment]
Retested with this translation and GlotDict active. Problem is no longer present, so can be closed for now
