### ISSUE TITLE
The "review" button is on the discussion page?

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#408]
https://translate.wordpress.org/locale/nl-be/default/discussions/?page=159

![image](https://github.com/Mte90/GlotDict/assets/4569581/f4d308fd-f1ee-4120-8de8-193338b103f7)

This button shouldn't be here right?

**Comment by Mte90** [comment]
The discussions page is new and our extension doesn't check that page.
The function to improve is https://github.com/Mte90/GlotDict/blob/b6ae61efe543d9b909fc08dedbb4edff11886151/js/glotdict-functions.js#L135
I think that the only way to be sure that is that page is to check if a class like `.discussions-table-head` exist so the button is not injected.
