### ISSUE TITLE
'ko_KR' locale missing

### ISSUE THREAD

**Issue by dalguji** [Mte90/GlotDict#411]
Browser: Chrome
Link: "**Pick locale glossary ->** " select box
Locale used: ko_KR

ko_KR locale is missing "Pick locale glossary -> " select box. Please help adding ko_KR locale to it.

https://github.com/Mte90/GlotDict/blob/3fc09a6808e21411aa47404672ffd25fae3928cc/js/glotdict-functions.js#L55

![Screen Shot 2024-05-02 PM 8 51 56](https://github.com/Mte90/GlotDict/assets/5715281/9787bc81-4122-47df-ad34-6b266c7920ef)

**Comment by Mte90** [comment]
Hi, that list is generated with https://github.com/Mte90/GlotDictjson
The locale is added when there is a glossary for that language on wordpress.org, are you able to share me a link for it?

**Comment by dalguji** [comment]
Sure, the link is https://translate.wordpress.org/locale/ko/default/glossary/

**Comment by Mte90** [comment]
Added on the generator online https://github.com/Mte90/GlotDictJSON/commit/6a9872163c385551bcbda6687a9abe0cf57344ec

Also updated in the glotdict so in the next version there will be as default.
Anyway there is a cache system in GlotDict that run everyday and will check for the last locale list so just tomorrow it should be updated in your instance, that line in the code is just a prefill just in case.
