### ISSUE TITLE
Shortcut for aprove is not working

### ISSUE THREAD

**Issue by mobby2561** [Mte90/GlotDict#43]
The Ctrl+Shift+A shortcut is not working anymore in Firefox.
Now it opens tab with addons manager.

**Comment by Mte90** [comment]
With firefox 49 is working, what is your version of firefox?

**Comment by mobby2561** [comment]
I'm using version 48.02

**Comment by mobby2561** [comment]
Here it is also described. It's the second shortcut in tools section.
[https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_tools](url)

**Comment by Mte90** [comment]
I know that hotkey is used for the addon manager but with the new js library that I use this should be overwrite that hotkey. 
I have to investigate.

**Comment by mobby2561** [comment]
I've pushed Ctrl+Alt+R  and then tried to approve string using Ctrl+Shift+A shortcut worked.
So you can marke this issue as closed.
