### ISSUE TITLE
Strange behaviour (all of a sudden)

### ISSUE THREAD

**Issue by Presskopp** [Mte90/GlotDict#47]
![issue](https://cloud.githubusercontent.com/assets/18373563/18799766/b5b2d326-81d9-11e6-9b55-fdfca4e33522.gif)

Cleared cache (using Chrome 53.0.2785.116 m), restarted.. - but still..

**Comment by Mte90** [comment]
Link: https://translate.wordpress.org/projects/wp-plugins/mainwp-child/dev/de/default?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
Problem on chrome.

**Comment by Presskopp** [comment]
This is an example link. With chrome it's happening everywhere to me, but NOT on any string, just 2/5 or so, just like in the "video" above..

**Comment by Mte90** [comment]
Ok the problem happen with the de language only on chrome, i am investigating.

**Comment by Mte90** [comment]
Uhm I know find the problem that is the term wordpress in the glossary with the regex.
