### ISSUE TITLE
Bad display of Source translations in FF with GD 1.1.6

### ISSUE THREAD

**Issue by fxbenard** [Mte90/GlotDict#48]
https://translate.wordpress.org/projects/meta/plugins-v3/fr/default?filters[original_id]=3296919

WordPress search=Plugin&set=fr%2Fdefault">Plugin search=Directory&set=fr%2Fdefault">Directory Guidelines:

It happens it lots of strings in fact.

**Comment by Mte90** [comment]
Chrome?

**Comment by Mte90** [comment]
Ok the problem happen on Chrome with French, i fixed for chrome with german yesterday.

**Comment by fxbenard** [comment]
Firefox powa

**Comment by fxbenard** [comment]
Fixed in 1.1.7! Thanks for the reactivity.
