### ISSUE TITLE
Strange behaviour with html tag in the term

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#49]
Link: https://translate.wordpress.org/projects/meta/forums/de/default?filters%5Bterm%5D=error&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

Real text:
``<strong>ERROR<strong>: There was a problem sticking that topic! ``
Output:
``<strong>ERROR span class="notranslate"><strong>: There was a problem sticking that topic!``

The span class part is a bug.

**Comment by Mte90** [comment]
Another example: https://translate.wordpress.org/projects/wp-plugins/cookie-notice/dev-readme/it/default?filters[status]=either&filters[original_id]=678173&filters[translation_id]=43191066

**Comment by Presskopp** [comment]
https://translate.wordpress.org/projects/meta/forums/de/default?filters[status]=either&filters[original_id]=3414212&filters[translation_id]=45122418

Original string:
<strong>ERROR span class="notranslate"><strong>: There was a problem sticking that topic!

translated to:
<strong>FEHLER</strong>: Es gab ein Problem beim Anheften dieses Beitrags!

Warning: Expected <strong>, got </strong>.

**Comment by Mte90** [comment]
Ok the bug happen on german
