### ISSUE TITLE
'copy from original' appending whitespace

### ISSUE THREAD

**Issue by pixelverbieger** [Mte90/GlotDict#55]
the link/function 'copy from original' copies the original string into the translations field, but it appends an extra whitespace at the end of the pasted string

Firefox 49.0,
El Capitan 10.11.6

**Comment by Mte90** [comment]
Already fixed https://github.com/Mte90/GlotDict/issues/53 the glotdict 1.1.11 released yesterday (I hope that for today will be available also in firefox).
You have only to wait :-D

**Comment by pixelverbieger** [comment]
👍 thanks
