### ISSUE TITLE
Welsh Glossary

### ISSUE THREAD

**Issue by rprys** [Mte90/GlotDict#56]
When hovering over the highlighted word it offers a word from another language not Welsh (Turkish? New Post  > sonraki yazi) 
When you click through the highlighted word it offers the correct Welsh examples.

Could you have a look at the hover over action and link it to the Welsh glossary?
Thanks
Rhos

**Comment by Mte90** [comment]
can you share the link where happen? So I can test it :-)

**Comment by rprys** [comment]
I'm updating the translation of some themes, so try:
https://translate.wordpress.org/projects/wp-themes/resonar/cy/default?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

The attatched jpeg may not help  much but theme is thema in Welsh, screen is sgrin and obviously blog is blog ;-)
![welsh](https://cloud.githubusercontent.com/assets/16651092/19591642/e5e05bf8-976f-11e6-8494-b7757edd8f96.jpg)

Thanks

**Comment by Mte90** [comment]
You are right there is a typo, the bug is on https://github.com/Mte90/GlotDictjson but for tomorrow there will be avalaible new translations and finally also for welsh!
