### ISSUE TITLE
Keyboard shortcut SHIFT-ENTER no longer works

### ISSUE THREAD

**Issue by ntwb** [Mte90/GlotDict#62]
On translate.w.org if you press SHIFT-ENTER that will 'Add translation", this no longer works on a MAc

**Comment by Mte90** [comment]
What version are you using? the 1.1.13 had that problem the nexts fixed that issue.

**Comment by ntwb** [comment]
Currently I've got `GlotDict 1.1.15`, just re-confirmed that this issue still occurs with `1.1.5`

**Comment by Mte90** [comment]
As I can see the right hotkey is ctrl not shift https://github.com/Mte90/GlotDict

**Comment by ntwb** [comment]
Cool... Without this extension SHIFT-ENTER works, with this extension it is CTRL-ENTER

I think I can work with that, though should both work? Why does this extension stop SHIFT-ENTER from working?

**Comment by Mte90** [comment]
Now glotpress have their own hotkeys that have conflicts with the glotdict ones, so glotdict disable the official hotkey and replace with their one to avoid any problem.
