### ISSUE TITLE
Warning Translation is missing a final '.' when '...' is replaced with &hellip

### ISSUE THREAD

**Issue by ePascalC** [Mte90/GlotDict#67]
In the French language, when a string has '...' inside, it is replaced in the translation with '&hellip'.
GlotDict is giving a warning when the '...' is at the end of the string because it does not find a final '.' in the translation string.

Can you please adapt your check to NOT give this warning if the last 3 characters are '...' ?

Thanks.
![2017-01-30_16-24-17](https://cloud.githubusercontent.com/assets/18325208/22458477/01deb638-e79d-11e6-8a2a-1ba2e64da7cd.png)

**Comment by Mte90** [comment]
a link where I can replicate the bug?

**Comment by Mte90** [comment]
Ref: https://translate.wordpress.org/projects/wp-plugins/broken-link-checker/stable/fr-be/default?filters%5Boriginal_id%5D=582122****
