### ISSUE TITLE
In CJK, some additional char is used for punctuation marks

### ISSUE THREAD

**Issue by hinaloe** [Mte90/GlotDict#68]
in translate.w.org, with below case it say ” The translation it's missing of a final . or ? or !” with GlotDict.

orig: `Activate the plugin through the 'Plugins' menu in WordPress.`
translate: `WordPress の「プラグイン」メニュー内からプラグインを有効化。`
https://translate.wordpress.org/projects/wp-plugins/responsive-slide/stable-readme/ja/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3990625&filters%5Btranslation_id%5D=47701512

In japanese, `、` `。` is punctuation marks like `,` `.`. but it is not allowed the translation (should allow).

in other case, ? and ! has other width of char.
 (see: 
- https://en.wikipedia.org/wiki/Exclamation_mark#Unicode_and_HTML 
- https://en.wikipedia.org/wiki/Question_mark#Fullwidth_question_mark

)

They should be allow, and there are more other pattern. 
I think that should not block, but may be ask.

thank you.

ref #67 
Slack: https://wordpress.slack.com/archives/glotpress/p1486817794000581

**Comment by Mte90** [comment]
Thanks for the report, I don't know that fact.
I will release a fix very asap!

**Comment by mayukojpn** [comment]
Thanks @Mte90!
FYI: We don't need to use multibyte `！` or `？` which are mentioned in Hinaloe's comment. [Japanese translation guide line](https://wpdocs.osdn.jp/WordPress_%E3%81%AE%E7%BF%BB%E8%A8%B3/%E7%BF%BB%E8%A8%B3%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3) allows only `、` and `。` or other single byte marks.

**Comment by Mte90** [comment]
The extension is ready, the list for puntation mark is here: https://github.com/Mte90/GlotDict/blob/dc99155e9de5723df9addb50df644e5d5753b898/js/glotdict.js#L304
It's complete for your needs?

**Comment by mayukojpn** [comment]
It's fine for us, Thanks!
_(I found Chinese use multibyte ？ [like this](https://translate.wordpress.org/projects/wp/dev/zh-cn/default?filters%5Bterm%5D=%3F&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc))_ 🙇 We can ask other locale translator about other variation in next meeting!

**Comment by Mte90** [comment]
Perfect! For any issues, open a ticket and fast as I can I will release a new version :-)
For this fix I will release a new version so in the next hours you will receive the update :-)

**Comment by hinaloe** [comment]
Thanks them!
