### ISSUE TITLE
Problems on 1.2.0

### ISSUE THREAD

**Issue by ntwb** [Mte90/GlotDict#72]
I'm currently seeing 2 issues:

1. Strings from the glossary are no longer highlighted in blue on the left hand side
2. Ctrl+Enter is not working to "Add translation"

p.s. I ❤️ the recent changes & GlotDict @Mte90 😄

**Comment by Mte90** [comment]
The version 2.0 doesn't exist (yet) so I suppose that you're talking of the 1.2.0 I am right?

**Comment by ntwb** [comment]
Correct, my bad, v1.2 is the version I have installed, using #en-au

**Comment by Mte90** [comment]
* I tried right now on that page with en-au on https://translate.wordpress.org/projects/wp-plugins/geodirectory/stable/en-au/default and I get the blue on the Anonymize user ip string.
Can you give me examples (links) where there is that issue?
* the ctrl+enter is working to me. With what browser you have the issue?

For the future can you open a ticket for every issue?

**Comment by ntwb** [comment]
<img width="995" alt="screen shot 2017-03-10 at 4 55 04 pm" src="https://cloud.githubusercontent.com/assets/1016458/23781487/7ffa4900-05b2-11e7-8c3e-40682636d2be.png">

Via https://translate.wordpress.org/projects/wp-plugins/jetpack/dev-readme/en-au/default?filters%5Bterm%5D=customize&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=original&sort%5Bhow%5D=desc

The term `customize` should be highlighted blue, it should also be underlined though that's a GlotPress issue.

Also CTRL-ENTER doesn't work for me, I'm using Chrome 58.0.3026.3 dev on macOS

**Comment by Mte90** [comment]
There was an issue on the migration of the extension data to 1.2.0, the new release will fix all the issue that you reported :-)

**Comment by ntwb** [comment]
Thanks :)
