### ISSUE TITLE
Problems with Chrome vesion

### ISSUE THREAD

**Issue by wocmultimedia** [Mte90/GlotDict#74]
Hi,
this morning I tried to access this link https://translate.wordpress.org/projects/wp-plugins/elementor as usual to check strings to translate and I couldn't access the page, cause your extension had some issues.
The page is continuing charging and switching from Translate to GlotDict sections. I refreshed several times and also cleaned the cache. Maybe something is wrong with latest f..k.ng Chrome version.
I'm sure is the extension cause I can normally open this page on firefox and also it opens after deactivating GlotDict.
Regards,
Angelo
PS: I installed GlotDict in Firefox and it works correctly, so it's a conflict with Chrome. IMHO

**Comment by Mte90** [comment]
Yes bug already reported yesterday but today I will look on it :-)

**Comment by Mte90** [comment]
the version that I uploading now will fix this issue :-)
