### ISSUE TITLE
pt-br glossary seems to be mixed up with another language, maybe polish

### ISSUE THREAD

**Issue by sheilagomes** [Mte90/GlotDict#76]
Browser: Chrome
Link: https://translate.wordpress.org/projects/wp-plugins/wpclef/dev/pt-br/default?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
Locale used: pt-br
![image](https://cloud.githubusercontent.com/assets/26465317/24475224/94fa0488-14a5-11e7-8c34-39a117ee8ae8.png)

**Comment by Mte90** [comment]
There was a typo in https://github.com/Mte90/GlotDictJSON but now is fixed, tomorrow the pt-br locales will be pure pt-be :-)
sometimes when you have to work with 29 languages a typo can happen XD
