### ISSUE TITLE
GlotDict showing results in a different language than the one set

### ISSUE THREAD

**Issue by sheilagomes** [Mte90/GlotDict#77]
Browser: Chrome
Link: https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/dev/pt-br/default?filters%5Bterm%5D&filters%5Buser_login%5D&filters%5Bstatus%5D=waiting&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc&page=2
Locale used: pt-br

The language shown is Breton, when it should show pt-br, from what you can see in the link, after clicking in the term during the translation: https://translate.wordpress.org/consistency?search=slug&set=br%2Fdefault

**Comment by Mte90** [comment]
Dammit I have to check better the code, I was thinking to have fixed that issues -.-'
The code use https://github.com/Mte90/GlotDictJSON/blob/master/index.php#L40 this page https://translate.wordpress.org/locale/pt-br/default/glossary and here there is the json https://codeat.co/glotdict/dictionaries/1.0.1/pt_BR.json
As I can see the glossary is the same but why are you sayng that is breton? what are the wrong words?

**Comment by sheilagomes** [comment]
Hi Danielle, what happens is that the language shown during the translation in GlotPress is not pt-br and when I click on the word to open the glossary, it goes to Breton, hence my assumption that it's not correctly set

**Comment by Mte90** [comment]
The issues that breton doesn't exist in the code because they don't have a glossary but I now understand, the link on the consistency tool is wrong (br is from pt-br) but the glossary loaded is the right one.

**Comment by sheilagomes** [comment]
You're right, Danielle! I'm sorry, I was checking a word that is used untranslated in Portuguese. I'll close the issue then.
