### ISSUE TITLE
Wrong character set ?

### ISSUE THREAD

**Issue by ePascalC** [Mte90/GlotDict#78]
Browser: FF and Chrome
Locale used: fr_FR

**barre dàoutils** should be **barre d'outils**

<img width="166" alt="capture d ecran 2017-04-07 a 16 20 00" src="https://cloud.githubusercontent.com/assets/18325208/24808355/a8bacbe8-1bbb-11e7-9135-e71f41a29329.png">

**Comment by fxbenard** [comment]
Same for « é, è » etc. not displaying properly
