### ISSUE TITLE
Question: Should I actually be translating ... to &hellip;

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#82]
Hello,

I'm playing around with GlotDict on en_CA and came across this warning;
"`Warning: The translation contain a final ... that need to be translated as &hellip;`"

String Permalink - https://translate.wordpress.org/projects/apps/ios/dev/en-ca/default?filters%5Boriginal_id%5D=4595947

My Question - Should I actually be using `&hellip;` in the translation, or should this be flagged to the plugin developer to correct their source string?

Thanks

**Comment by Mte90** [comment]
HI, usually for web stuff is better to use that kind of stuff but you are translating the iOS app so will create issues use an ASCII term.
My suggestion is to open the settings of glotdict (top left in the blue header) and disable the check

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 found it on the right there.

I set-up two other tickets as suggestions;
#83 to suggest better verbiage for the message.
#84 to suggest adding the ability to Discard Warnings.

All the best

**Comment by ajoah** [comment]
Hi @Mte90,

Should not we use the character `…` instead of the ASCII term `&hellip` ?

**Comment by Mte90** [comment]
Good point I am tryiong to understand why I chosen to add that validator and I cannot find why.
I think that I added it after a private request because few locales use it.

**Comment by garrett-eclipse** [comment]
@Mte90 might be a good call to check with the #polyglots peeps and see what the general preference is. And if it's different depending on the locale we can have a setting control if it's the character … or the ASCII term.

**Comment by ajoah** [comment]
I think all locales want to avoid any ASCII characters. I believe that the initial request was to prevent use of `...` (three characters dot) instead of `…` (one character of three dots). But now we can forgot `&hellip;` and use `…`.

**Comment by Mte90** [comment]
Maybe we can add 2 validators for that and both disabled on new installation so the localizers can use what they prefer.
