### ISSUE TITLE
Better Verbiage for - Warning: The translation contain a final ... that need to be translated as &hellip;

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#83]
Hello,

Just wanted to propose better verbiage that's grammatically correct;

The string to change;
`Warning: The translation contain a final ... that need to be translated as &hellip;`

Idea One;
`Warning: The translation contains a final ... that needs to be translated as &hellip;`

Idea Two;
`Warning: The translation contains a final ... that should be translated as &hellip;`

*IMHO Idea Two is better in that Glossary rules are suggestions and not requirements so saying should instead of need conveys that.

Thanks

**Comment by Mte90** [comment]
You are right, my english sometimes is not very good :-)
the next version will fix that :-)

**Comment by garrett-eclipse** [comment]
No worries @Mte90 is there a list of all Warnings or a file I should look into I wouldn't mind doing a cursory review for you.

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 went through and provided two more.
