### ISSUE TITLE
Provide a Discard on Warnings

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#84]
Hello,

I wanted to suggest that Warnings come with the 'Discard' capability that the normal translate.wordpress.org site has.

Current warning from GlotDict;
![screen shot 2017-06-06 at 9 18 09 am](https://user-images.githubusercontent.com/8726005/26839931-56139624-4a99-11e7-84f5-1ceb37b1b506.png)

Standard non-GlotDict warning w/ Discard link;
![screen shot 2017-06-06 at 9 19 45 am](https://user-images.githubusercontent.com/8726005/26839947-61ccd886-4a99-11e7-811d-81f36525390c.png)

Thank you

**Comment by Mte90** [comment]
Good point, I plan for that feature for next releases
