### ISSUE TITLE
Page Up/Page Down keybinding isn't working on Chrome

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#86]
Browser: Chrome - Version 58.0.3029.110 (64-bit)
Link: https://translate.wordpress.org/projects/wp-plugins/duplicator/dev-readme/en-ca/default?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
Locale used: en_CA

When I open a string and then hit page up or page down I was expecting it to jump to the next string as the hotkey list suggested. This doesn't happen however. Other hotkeys seem to work fine.

Thanks

**Comment by Mte90** [comment]
Thanks I will verify this behavious asap

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 
I tested and is now working properly.
Cheers
