### ISSUE TITLE
Row Highlighting (blue line) doesn't pick up rows containing the WP URL Glossary Term

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#93]
Browser: Google Chrome Version 59.0.3071.109
Link: https://translate.wordpress.org/projects/wp-plugins/debug-media/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2890125
Locale used: en_CA

I've now noticed this on two plugins where the row containing a wp.org link (which is a Glossary Term) isn't denoted with the left side blue line. If you open the row GlotDict & GlotPress highlight/underline the term so it is being detected just not getting the blue line. Other rows with terms contained are being blue-lined as expected.

Here's a list of all instances I've found so far;
https://translate.wordpress.org/projects/wp-plugins/debug-media/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2890125
https://translate.wordpress.org/projects/wp-plugins/debug-bar-elasticpress/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2123614
https://translate.wordpress.org/projects/wp-plugins/debug-bar-elasticpress/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2123613
https://translate.wordpress.org/projects/wp-plugins/debug-bar-elasticpress/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2123610
https://translate.wordpress.org/projects/wp-plugins/debug-bar-elasticpress/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2123609
https://translate.wordpress.org/projects/wp-plugins/debug-bar-elasticpress/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2123607

**Comment by Mte90** [comment]
I don't understand the problem, the term is highlighted and there is a link so maybe is something that my english doesn't help to understand XD

**Comment by garrett-eclipse** [comment]
Hi @Mte90, sorry about that. The highlight is fine it's just the blue border on the left that's missing from these instances. Other terms place a blue border on the left of the row containing the term.
![screen shot 2017-07-06 at 1 52 33 pm](https://user-images.githubusercontent.com/8726005/27932407-84151f86-6252-11e7-8126-c5b5dd2c5d93.png)

**Comment by Mte90** [comment]
Gotcha the problem

**Comment by garrett-eclipse** [comment]
Thanks @Mte90
