### ISSUE TITLE
Remove review warnings when review mode disabled

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#97]
Hi @Mte90 

I noticed when you have an untranslated string open and enable Review mode that it adds a warning about 'The translation seems empty!', but when you disable Review mode the warning stays until you reload. Might want to have all featurs added by Review mode get removed upon disabling review mode.

![screen shot 2017-07-14 at 12 01 18 pm](https://user-images.githubusercontent.com/8726005/28226832-6387f8e8-688c-11e7-9994-f446237ddd1f.png)

Alternate question, when dealing with untranslated string in Review mode should a warning really be added about it being empty. Or should that only be if it's in a 'current' state.

Thanks

**Comment by Mte90** [comment]
Uhm usually when I do the review I use the filter for string that wait the review so I never used in other lists.
So yes I have to check for strings that are not translated and not execute the validation.
I think that is a bug that I need to fix :-)

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 if it's just the view that's introducing issues and the Review feature is only meant for the 'Waiting' filter then maybe we just disable the feature unless you're on that view. Just a thought, although I guess the review feature could be helpful in other views as well.
