### ISSUE TITLE
kind of false positive when URL contains a glossary term

### ISSUE THREAD

**Issue by pixelverbieger** [Mte90/GlotDict#98]
Browser: any
Link: https://translate.wordpress.org/projects/wp-plugins/file-renaming-on-upload/stable-readme/de/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4309752&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc
Locale used: de_DE

an URL/path containing a glossary term produces a warning about missing translation of this term
![false-positive](https://user-images.githubusercontent.com/21057107/28257201-44f44e42-6ac9-11e7-9829-d2ba20a45ece.jpg)

**Comment by Mte90** [comment]
This is a bug of glotpress and not GlotDict, now glotdict don't add anymore tooltips in the text.

**Comment by Mte90** [comment]
This is a bug of GP that add tooltips inside path that is on text and GlotDict doesn't consider this things.
Bug reported on GP :-)
