### ISSUE TITLE
alert if the longer one of two glossary terms is missing

### ISSUE THREAD

**Issue by pixelverbieger** [Mte90/GlotDict#99]
Browser: Firefox (Mac)
Link: https://translate.wordpress.org/projects/wp-plugins/geneanet-embedded-individual/stable/de/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4792243&filters%5Btranslation_id%5D=50572741
Locale used: de_DE

![verb-noun](https://user-images.githubusercontent.com/21057107/28270826-1a37e860-6b07-11e7-8e8c-079e4afb7789.jpg)

**Comment by Mte90** [comment]
Uhm the actual behaviour is that that get the first term.
Probably is better to check for all the occurrence if one of them exist in the translation to avoid that wrong warning.
